In [61]:
import pandas as pd
from sklearn.model_selection import TimeSeriesSplit, GridSearchCV
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from sklearn.linear_model import ElasticNet

In [62]:
df = pd.read_csv('aggregate_blog.csv')

In [64]:
X = df[['year','month_sin','month_cos','ai_pct_lag1','ai_pct_lag2','ai_pct_ma3','time_index']]
y = df['ai_percentage']

In [65]:
tscv = TimeSeriesSplit(n_splits=5)

pipeline = Pipeline([
    ('scaler', StandardScaler()), 
    ('svr', SVR())
])


param_grid = {
    'svr__kernel': ['rbf', 'linear'],
    'svr__C': [0.001, 0.1, 1, 5, 3, 10],
    'svr__gamma': ['scale', 'auto']
}

scoring = {
    'MAE': 'neg_mean_absolute_error',
    'RMSE': 'neg_root_mean_squared_error',
    'R2': 'r2'
}

model = GridSearchCV(
    pipeline,
    param_grid,
    cv=tscv,
    scoring=scoring,
    refit='RMSE',
)

model.fit(X, y)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('svr', SVR())]),
             param_grid={'svr__C': [0.001, 0.1, 1, 5, 3, 10],
                         'svr__gamma': ['scale', 'auto'],
                         'svr__kernel': ['rbf', 'linear']},
             refit='RMSE',
             scoring={'MAE': 'neg_mean_absolute_error', 'R2': 'r2',
                      'RMSE': 'neg_root_mean_squared_error'})

In [66]:
pd.set_option('display.max_columns', None)
pd.DataFrame(model.cv_results_).sort_values('rank_test_RMSE')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_svr__C,param_svr__gamma,param_svr__kernel,params,split0_test_MAE,split1_test_MAE,split2_test_MAE,split3_test_MAE,split4_test_MAE,mean_test_MAE,std_test_MAE,rank_test_MAE,split0_test_RMSE,split1_test_RMSE,split2_test_RMSE,split3_test_RMSE,split4_test_RMSE,mean_test_RMSE,std_test_RMSE,rank_test_RMSE,split0_test_R2,split1_test_R2,split2_test_R2,split3_test_R2,split4_test_R2,mean_test_R2,std_test_R2,rank_test_R2
21,0.004547,0.004358,0.003646,0.004654,10.000,scale,linear,"{'svr__C': 10, 'svr__gamma': 'scale', 'svr__ke...",-0.083773,-0.127796,-0.065458,-0.090521,-0.032882,-0.080086,0.031116,1,-0.096435,-0.152771,-0.082335,-0.127997,-0.036564,-0.099220,0.039785,1,0.999754,0.999840,0.999784,0.999817,0.999884,0.999816,0.000045,1
23,0.004502,0.005514,0.002213,0.004427,10.000,auto,linear,"{'svr__C': 10, 'svr__gamma': 'auto', 'svr__ker...",-0.083773,-0.127796,-0.065458,-0.090521,-0.032882,-0.080086,0.031116,1,-0.096435,-0.152771,-0.082335,-0.127997,-0.036564,-0.099220,0.039785,1,0.999754,0.999840,0.999784,0.999817,0.999884,0.999816,0.000045,1
13,0.004523,0.004334,0.000000,0.000000,5.000,scale,linear,"{'svr__C': 5, 'svr__gamma': 'scale', 'svr__ker...",-0.226326,-0.128451,-0.066108,-0.121676,-0.056934,-0.119899,0.060434,3,-0.267255,-0.174491,-0.081867,-0.165044,-0.068699,-0.151471,0.071855,3,0.998110,0.999792,0.999786,0.999695,0.999592,0.999395,0.000646,3
15,0.002397,0.003139,0.002256,0.003525,5.000,auto,linear,"{'svr__C': 5, 'svr__gamma': 'auto', 'svr__kern...",-0.226326,-0.128451,-0.066108,-0.121676,-0.056934,-0.119899,0.060434,3,-0.267255,-0.174491,-0.081867,-0.165044,-0.068699,-0.151471,0.071855,3,0.998110,0.999792,0.999786,0.999695,0.999592,0.999395,0.000646,3
19,0.007875,0.005328,0.003890,0.004270,3.000,auto,linear,"{'svr__C': 3, 'svr__gamma': 'auto', 'svr__kern...",-1.477966,-0.186776,-0.074931,-0.201060,-0.067818,-0.401710,0.540935,5,-1.738607,-0.249070,-0.089812,-0.269791,-0.082132,-0.485882,0.631186,5,0.920027,0.999576,0.999743,0.999185,0.999417,0.983590,0.031782,5
17,0.004768,0.005853,0.000402,0.000803,3.000,scale,linear,"{'svr__C': 3, 'svr__gamma': 'scale', 'svr__ker...",-1.477966,-0.186776,-0.074931,-0.201060,-0.067818,-0.401710,0.540935,5,-1.738607,-0.249070,-0.089812,-0.269791,-0.082132,-0.485882,0.631186,5,0.920027,0.999576,0.999743,0.999185,0.999417,0.983590,0.031782,5
11,0.005354,0.004995,0.002179,0.003533,1.000,auto,linear,"{'svr__C': 1, 'svr__gamma': 'auto', 'svr__kern...",-4.129964,-2.939806,-1.888989,-4.104745,-1.491042,-2.910909,1.092934,7,-4.825132,-3.865822,-2.180308,-5.821879,-1.852066,-3.709042,1.517874,7,0.384033,0.897813,0.848273,0.620497,0.703597,0.690843,0.182682,7
9,0.003120,0.000805,0.003539,0.001277,1.000,scale,linear,"{'svr__C': 1, 'svr__gamma': 'scale', 'svr__ker...",-4.129964,-2.939806,-1.888989,-4.104745,-1.491042,-2.910909,1.092934,7,-4.825132,-3.865822,-2.180308,-5.821879,-1.852066,-3.709042,1.517874,7,0.384033,0.897813,0.848273,0.620497,0.703597,0.690843,0.182682,7
7,0.004796,0.003277,0.001399,0.001954,0.100,auto,linear,"{'svr__C': 0.1, 'svr__gamma': 'auto', 'svr__ke...",-4.909179,-6.728365,-8.501296,-6.507631,-3.314157,-5.992126,1.757727,9,-5.456120,-10.406827,-9.611594,-9.034988,-4.246378,-7.751181,2.437733,9,0.212398,0.259456,-1.948607,0.086005,-0.558139,-0.389777,0.832921,9
5,0.001261,0.002521,0.005213,0.003692,0.100,scale,linear,"{'svr__C': 0.1, 'svr__gamma': 'scale', 'svr__k...",-4.909179,-6.728365,-8.501296,-6.507631,-3.314157,-5.992126,1.757727,9,-5.456120,-10.406827,-9.611594,-9.034988,-4.246378,-7.751181,2.437733,9,0.212398,0.259456,-1.948607,0.086005,-0.558139,-0.389777,0.832921,9
22,0.003768,0.005739,0.002976,0.004133,10.000,auto,rbf,"{'svr__C': 10, 'svr__gamma': 'auto', 'svr__ker...",-5.243830,-7.505943,-9.166493,-6.130175,-3.199168,-6.249122,2.020774,11,-6.012000,-11.238430,-10.581710,-8.218668,-3.858191,-7.981800,2.767871,11,0.043738,0.136375,-2.573862,0.243704,-0.286283,-0.487266,1.058252,11
20,0.004242,0.004112,0.004428,0.005438,10.000,scale,rbf,"{'svr__C': 10, 'svr__gamma': 'scale', 'svr__ke...",-5.243830,-7.505943,-9.166493,-6.130175,-3.199168,-6.249122,2.020774,11,-6.012000,-11.238430,-10.581710,-8.218668,-3.858191,-7.981800,2.767871,11,0.043738,0.136375,-2.573862,0.243704,-0.286283,-0.487266,1.058252,11
14,0.000401,0.000802,0.003093,0.005238,5.000,auto,rbf,"{'svr__C': 5, 'svr__gamma': 'auto', 'svr__kern...",-5.223132,-7.536125,-10.102216,-6.419786,-4.153558,-6.686963,2.050237,13,-6.125382,-11.663277,-11.411669,-8.385667,-4.971263,-8.511452,2.705082,13,0.007329,0.069845,-3.156468,0.212657,-1.135514,-0.800430,1.272745,13
12,0.003194,0.004243,0.001752,0.002618,5.000,scale,rbf,"{'svr__C': 5, 'svr__gamma': 'scale', 'svr__ker...",-5.223132,-7.536125,-10.102216,-6.419786,-4.153558,-6.686963,2.050237,13,-6.125382,-11.663277,-11.411669,-8.385667,-4.971263,-8.511452,2.705082,13,0.007329,0.069845,-3.156468,0.212657,-1.135514,-0.800430,1.272745,13
16,0.000000,0.000000,0.000000,0.000000,3.000,scale,rbf,"{'svr__C': 3, 'svr__gamma': 'scale', 'svr__ker...",-5.221400,-7.555546,-10.962539,-6.367924,-5.077421,-7.036966,2.156977,15,-6.188995,-12.083409,-12.179000,-8.620299,-5.913072,-8.996955,2.727213,15,-0.013396,0.001627,-3.734229,0.167981,-2.021310,-1.119866,1.535452,15
18,0.002362,0.003143,0.003326,0.005086,3.000,auto,rbf,"{'svr__C': 3, 'svr__gamma': 'auto', 'svr__kern...",-5.221400,-7.555546,-10.962539,-6.367924,-5.077421,-7.036966,2.156977,15,-6.188995,-12.083409,-12.179000,-8.620299,-5.913072,-8.996955,2.727213,15,-0.013396,0.001627,-3.734229,0.167981,-2.021310,-1.119866,1.535452,15
8,0.000805,0.001610,0.005317,0.005160,1.000,scale,rbf,"{'svr__C': 1, 'svr__gamma': 'scale', 'svr__ker...",-5.272467,-7.616977,-12.560671,-6.623803,-6.347044,-7.684193,2.550034,17,-6.264819,-12.643347,-13.684248,-9.423578,-7.219853,-9.847169,2.914009,17,-0.038379,-0.093045,-4.976789,0.005693,-3.504283,-1.721361,2.109179,17
10,0.003115,0.004482,0.003194,0.004643,1.000,auto,rbf,"{'svr__C': 1, 'svr__gamma': 'auto', 'svr__kern...",-5.272467,-7.616977,-12.560671,-6.623803,-6.347044,-7.684193,2.550034,17,-6.264819,-12.643347,-13.684248,-9.423578,-7.219853,-9.847169,2.914009,17,-0.038379,-0.093045,-4.976789,0.005693,-3.504283,-1.721361,2.109179,17
6,0.004846,0.003972,0.000287,0.000575,0.100,auto,rbf,"{'svr__C': 0.1, 'svr__gamma': 'auto', 'svr__ke...",-5.349384,-7.624829,-13.286276,-9.017797,-7.419593,-8.539576,2.646821,19,-6.254702,-12.940983,-14.410824,-11.514953,-8.170906,-10.658474,3.020091,19,-0.035028,-0.145113,-5.628323,-0.484612,-4.769117,-2.212439,2.457853,19
4,0.000958,0.001916,0.004535,0.005689,0.100,scale,rbf,"{'svr__C': 0.1, 'svr__gamma': 'scale', 'svr__k...",-5.349384,-7.624829,-13.286276,-9.017797,-7.419593,-8.539576,2.646821,19,-6.254702,-12.940983,-14.410824,-11.514953,-8.170906,-10.658474,3.020091,19,-0.035028,-0.145113,-5.628323,-0.484612,-4.769117,-2.212439,2.457853,19
3,0.003337,0.004454,0.003526,0.003063,0.001,auto,linear,"{'svr__C': 0.001, 'svr__gamma': 'auto', 'svr__...",-5.352865,-7.633209,-13.336172,-9.114590,-8.037222,-8.694812,2.624747,21,-6.241470,-12.926941,-14.456706,-11.612851,-8.725309,-10.792656,2.954331,21,-0.030654,-0.142630,-5.670598,-0.509963,-5.578556,-2.386480,2.648806,21
1,0.003203,0.003829,0.004755,0.003196,0.001,scale,linear,"{'svr__C': 0.001, 'svr__gamma': 'scale', 'svr_...",-5.352865,-7.633209,-13.336172,-9.114590,-8.037222,-8.694812,2.624747,21,-6.241470,-12.926941,-14.456706,-11.612851,-8.725309,-10.792656,2.954331,21,-0.030654,-0.142630,-5.670598,-0.509963,-5.578556,-2.386480,2.648806,21
2,0.001153,0.001514,0.003330,0.003006,0.001,auto,rbf,"{'svr__C': 0.001, 'svr__gamma': 'auto', 'svr__...",-5.357845,-7.640519,-13.382316,-9.155293,-8.310278,-8.769250,2.628756,23,-6.254003,-12.959189,-14.505707,-11.656656,-8.979699,-10.871051,2.935390,23,-0.034797,-0.148338,-5.715894,-0.521376,-5.967748,-2.477631,2.752717,23
0,0.008711,0.004524,0.002631,0.004438,0.001,scale,rbf,"{'svr__C': 0.001, 'svr__gamma': 'scale', 'svr_...",-5.357845,-7.640519,-13.382316,-9.155293,-8.310278,-8.769250,2.628756,23,-6.254003,-12.959189,-14.505707,-11.656656,-8.979699,-10.871051,2.935390,23,-0.034797,-0.148338,-5.715894,-0.521376,-5.967748,-2.477631,2.752717,23

In [67]:
pipeline = Pipeline([
    ('scaler', StandardScaler()), 
    ('knn', KNeighborsRegressor())
])


param_grid = {
    'knn__n_neighbors': [5, 7, 9, 11],  
    'knn__weights': ['uniform'],  
    'knn__p': [1, 2],
    'knn__algorithm': ['ball_tree'],  
    'knn__leaf_size': [10,20, 30]  
}

scoring = {
    'MAE': 'neg_mean_absolute_error',
    'RMSE': 'neg_root_mean_squared_error',
    'R2': 'r2'
}

tscv = TimeSeriesSplit(n_splits=5)

model = GridSearchCV(
    pipeline, 
    param_grid,
    cv=tscv,
    scoring=scoring,
    refit='RMSE',
    n_jobs=-1,
    verbose=2,
    return_train_score=True
)

model.fit(X, y)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('knn', KNeighborsRegressor())]),
             n_jobs=-1,
             param_grid={'knn__algorithm': ['ball_tree'],
                         'knn__leaf_size': [10, 20, 30],
                         'knn__n_neighbors': [5, 7, 9, 11], 'knn__p': [1, 2],
                         'knn__weights': ['uniform']},
             refit='RMSE', return_train_score=True,
             scoring={'MAE': 'neg_mean_absolute_error', 'R2': 'r2',
                      'RMSE': 'neg_root_mean_squared_error'},
             verbose=2)

In [68]:
pd.DataFrame(model.cv_results_).sort_values('rank_test_RMSE')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_knn__algorithm,param_knn__leaf_size,param_knn__n_neighbors,param_knn__p,param_knn__weights,params,split0_test_MAE,split1_test_MAE,split2_test_MAE,split3_test_MAE,split4_test_MAE,mean_test_MAE,std_test_MAE,rank_test_MAE,split0_train_MAE,split1_train_MAE,split2_train_MAE,split3_train_MAE,split4_train_MAE,mean_train_MAE,std_train_MAE,split0_test_RMSE,split1_test_RMSE,split2_test_RMSE,split3_test_RMSE,split4_test_RMSE,mean_test_RMSE,std_test_RMSE,rank_test_RMSE,split0_train_RMSE,split1_train_RMSE,split2_train_RMSE,split3_train_RMSE,split4_train_RMSE,mean_train_RMSE,std_train_RMSE,split0_test_R2,split1_test_R2,split2_test_R2,split3_test_R2,split4_test_R2,mean_test_R2,std_test_R2,rank_test_R2,split0_train_R2,split1_train_R2,split2_train_R2,split3_train_R2,split4_train_R2,mean_train_R2,std_train_R2
1,0.007214,0.005091,0.004265,0.004136,ball_tree,10,5,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.146624,-6.947303,-5.227394,-8.116431,-2.700404,-5.627631,1.838253,4,-3.605405,-3.313980,-4.336922,-4.552465,-4.653135,-4.092381,0.534598,-5.676294,-10.246322,-5.794520,-9.995613,-3.552920,-7.053134,2.630054,1,-4.606076,-3.942323,-6.216377,-5.925910,-5.970782,-5.332294,0.894546,0.147550,0.282123,-0.071670,-0.118684,-0.090786,0.029707,0.157745,1,0.159914,0.501658,0.445049,0.550558,0.574593,0.446354,0.149941
9,0.012615,0.010488,0.003543,0.003715,ball_tree,20,5,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.146624,-6.947303,-5.227394,-8.116431,-2.700404,-5.627631,1.838253,4,-3.605405,-3.313980,-4.336922,-4.552465,-4.653135,-4.092381,0.534598,-5.676294,-10.246322,-5.794520,-9.995613,-3.552920,-7.053134,2.630054,1,-4.606076,-3.942323,-6.216377,-5.925910,-5.970782,-5.332294,0.894546,0.147550,0.282123,-0.071670,-0.118684,-0.090786,0.029707,0.157745,1,0.159914,0.501658,0.445049,0.550558,0.574593,0.446354,0.149941
17,0.008119,0.006485,0.001521,0.002063,ball_tree,30,5,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.146624,-6.947303,-5.227394,-8.116431,-2.700404,-5.627631,1.838253,4,-3.605405,-3.313980,-4.336922,-4.552465,-4.653135,-4.092381,0.534598,-5.676294,-10.246322,-5.794520,-9.995613,-3.552920,-7.053134,2.630054,1,-4.606076,-3.942323,-6.216377,-5.925910,-5.970782,-5.332294,0.894546,0.147550,0.282123,-0.071670,-0.118684,-0.090786,0.029707,0.157745,1,0.159914,0.501658,0.445049,0.550558,0.574593,0.446354,0.149941
8,0.014845,0.015812,0.013717,0.019299,ball_tree,20,5,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-4.846526,-7.481125,-5.595275,-6.891041,-3.123272,-5.587448,1.543150,1,-3.751313,-3.457240,-4.189818,-4.033416,-4.562626,-3.998883,0.376861,-5.528764,-10.551026,-6.359605,-8.851471,-4.049613,-7.068096,2.336406,4,-4.526342,-4.128469,-5.934645,-5.371374,-5.895759,-5.171318,0.728153,0.191286,0.238792,-0.290881,0.122758,-0.417085,-0.031026,0.269236,4,0.188747,0.453486,0.494211,0.630738,0.585216,0.470480,0.154320
16,0.004107,0.003448,0.004417,0.004181,ball_tree,30,5,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-4.846526,-7.481125,-5.595275,-6.891041,-3.123272,-5.587448,1.543150,1,-3.751313,-3.457240,-4.189818,-4.033416,-4.562626,-3.998883,0.376861,-5.528764,-10.551026,-6.359605,-8.851471,-4.049613,-7.068096,2.336406,4,-4.526342,-4.128469,-5.934645,-5.371374,-5.895759,-5.171318,0.728153,0.191286,0.238792,-0.290881,0.122758,-0.417085,-0.031026,0.269236,4,0.188747,0.453486,0.494211,0.630738,0.585216,0.470480,0.154320
0,0.018001,0.014105,0.017452,0.017359,ball_tree,10,5,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-4.846526,-7.481125,-5.595275,-6.891041,-3.123272,-5.587448,1.543150,1,-3.751313,-3.457240,-4.189818,-4.033416,-4.562626,-3.998883,0.376861,-5.528764,-10.551026,-6.359605,-8.851471,-4.049613,-7.068096,2.336406,4,-4.526342,-4.128469,-5.934645,-5.371374,-5.895759,-5.171318,0.728153,0.191286,0.238792,-0.290881,0.122758,-0.417085,-0.031026,0.269236,4,0.188747,0.453486,0.494211,0.630738,0.585216,0.470480,0.154320
3,0.018813,0.024455,0.007984,0.005062,ball_tree,10,7,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.469424,-8.042781,-6.727006,-7.159108,-2.826284,-6.044921,1.810465,13,-3.554675,-3.428198,-4.372822,-4.878354,-5.010933,-4.248996,0.655403,-6.014410,-11.485912,-7.605939,-9.010890,-3.618910,-7.547212,2.662337,7,-4.509860,-4.229217,-6.315787,-6.539347,-6.541462,-5.627135,1.033909,0.042971,0.097920,-0.846425,0.090874,-0.131682,-0.149268,0.358347,7,0.194644,0.426487,0.427157,0.452691,0.489387,0.398073,0.104267
11,0.009733,0.008821,0.006285,0.006218,ball_tree,20,7,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.469424,-8.042781,-6.727006,-7.159108,-2.826284,-6.044921,1.810465,13,-3.554675,-3.428198,-4.372822,-4.878354,-5.010933,-4.248996,0.655403,-6.014410,-11.485912,-7.605939,-9.010890,-3.618910,-7.547212,2.662337,7,-4.509860,-4.229217,-6.315787,-6.539347,-6.541462,-5.627135,1.033909,0.042971,0.097920,-0.846425,0.090874,-0.131682,-0.149268,0.358347,7,0.194644,0.426487,0.427157,0.452691,0.489387,0.398073,0.104267
19,0.011927,0.007280,0.017194,0.029145,ball_tree,30,7,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.469424,-8.042781,-6.727006,-7.159108,-2.826284,-6.044921,1.810465,13,-3.554675,-3.428198,-4.372822,-4.878354,-5.010933,-4.248996,0.655403,-6.014410,-11.485912,-7.605939,-9.010890,-3.618910,-7.547212,2.662337,7,-4.509860,-4.229217,-6.315787,-6.539347,-6.541462,-5.627135,1.033909,0.042971,0.097920,-0.846425,0.090874,-0.131682,-0.149268,0.358347,7,0.194644,0.426487,0.427157,0.452691,0.489387,0.398073,0.104267
18,0.002257,0.004514,0.004484,0.005492,ball_tree,30,7,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.062547,-6.959034,-6.938904,-7.593754,-2.856143,-5.882076,1.734039,10,-3.852179,-3.386029,-4.199377,-4.227898,-4.594280,-4.051953,0.407474,-5.957545,-10.942288,-7.530811,-9.773937,-3.809133,-7.602743,2.567878,10,-4.648715,-4.092367,-6.146025,-5.923847,-6.138244,-5.389840,0.854376,0.060983,0.181290,-0.810129,-0.069616,-0.253779,-0.178250,0.347355,10,0.144288,0.463003,0.457538,0.550871,0.550396,0.433219,0.150021
10,0.005136,0.004670,0.001057,0.001354,ball_tree,20,7,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.062547,-6.959034,-6.938904,-7.593754,-2.856143,-5.882076,1.734039,10,-3.852179,-3.386029,-4.199377,-4.227898,-4.594280,-4.051953,0.407474,-5.957545,-10.942288,-7.530811,-9.773937,-3.809133,-7.602743,2.567878,10,-4.648715,-4.092367,-6.146025,-5.923847,-6.138244,-5.389840,0.854376,0.060983,0.181290,-0.810129,-0.069616,-0.253779,-0.178250,0.347355,10,0.144288,0.463003,0.457538,0.550871,0.550396,0.433219,0.150021
2,0.005945,0.003452,0.004329,0.003253,ball_tree,10,7,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.062547,-6.959034,-6.938904,-7.593754,-2.856143,-5.882076,1.734039,10,-3.852179,-3.386029,-4.199377,-4.227898,-4.594280,-4.051953,0.407474,-5.957545,-10.942288,-7.530811,-9.773937,-3.809133,-7.602743,2.567878,10,-4.648715,-4.092367,-6.146025,-5.923847,-6.138244,-5.389840,0.854376,0.060983,0.181290,-0.810129,-0.069616,-0.253779,-0.178250,0.347355,10,0.144288,0.463003,0.457538,0.550871,0.550396,0.433219,0.150021
12,0.009282,0.010376,0.011208,0.014472,ball_tree,20,9,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.309839,-7.388189,-6.578596,-6.811546,-3.040664,-5.825767,1.549365,7,-3.807648,-3.797452,-4.286905,-4.146082,-4.810979,-4.169813,0.372876,-6.085293,-11.322239,-7.800495,-8.962253,-4.047204,-7.643497,2.476216,13,-4.662471,-4.534900,-6.389801,-5.768357,-6.535369,-5.578180,0.841197,0.020280,0.123446,-0.942095,0.100662,-0.415400,-0.222621,0.409410,13,0.139216,0.340585,0.413653,0.574139,0.490338,0.391586,0.148227
4,0.002370,0.003911,0.003290,0.004190,ball_tree,10,9,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.309839,-7.388189,-6.578596,-6.811546,-3.040664,-5.825767,1.549365,7,-3.807648,-3.797452,-4.286905,-4.146082,-4.810979,-4.169813,0.372876,-6.085293,-11.322239,-7.800495,-8.962253,-4.047204,-7.643497,2.476216,13,-4.662471,-4.534900,-6.389801,-5.768357,-6.535369,-5.578180,0.841197,0.020280,0.123446,-0.942095,0.100662,-0.415400,-0.222621,0.409410,13,0.139216,0.340585,0.413653,0.574139,0.490338,0.391586,0.148227
20,0.009518,0.004924,0.010372,0.010637,ball_tree,30,9,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.309839,-7.388189,-6.578596,-6.811546,-3.040664,-5.825767,1.549365,7,-3.807648,-3.797452,-4.286905,-4.146082,-4.810979,-4.169813,0.372876,-6.085293,-11.322239,-7.800495,-8.962253,-4.047204,-7.643497,2.476216,13,-4.662471,-4.534900,-6.389801,-5.768357,-6.535369,-5.578180,0.841197,0.020280,0.123446,-0.942095,0.100662,-0.415400,-0.222621,0.409410,13,0.139216,0.340585,0.413653,0.574139,0.490338,0.391586,0.148227
5,0.005896,0.003949,0.001829,0.002261,ball_tree,10,9,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.418130,-8.164663,-6.978488,-6.686384,-3.180012,-6.085535,1.695208,22,-3.704351,-3.853661,-4.461207,-4.814018,-5.236791,-4.414006,0.575640,-5.994630,-11.750194,-7.955090,-9.417033,-4.186333,-7.860656,2.628400,16,-4.549958,-4.649225,-6.423465,-6.290484,-6.807066,-5.744040,0.950231,0.049256,0.055930,-1.019837,0.007074,-0.514386,-0.284392,0.425645,16,0.180259,0.306919,0.407458,0.493556,0.447080,0.367054,0.111846
13,0.004516,0.003199,0.001452,0.002051,ball_tree,20,9,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.418130,-8.164663,-6.978488,-6.686384,-3.180012,-6.085535,1.695208,22,-3.704351,-3.853661,-4.461207,-4.814018,-5.236791,-4.414006,0.575640,-5.994630,-11.750194,-7.955090,-9.417033,-4.186333,-7.860656,2.628400,16,-4.549958,-4.649225,-6.423465,-6.290484,-6.807066,-5.744040,0.950231,0.049256,0.055930,-1.019837,0.007074,-0.514386,-0.284392,0.425645,16,0.180259,0.306919,0.407458,0.493556,0.447080,0.367054,0.111846
21,0.004434,0.001631,0.004550,0.004521,ball_tree,30,9,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.418130,-8.164663,-6.978488,-6.686384,-3.180012,-6.085535,1.695208,22,-3.704351,-3.853661,-4.461207,-4.814018,-5.236791,-4.414006,0.575640,-5.994630,-11.750194,-7.955090,-9.417033,-4.186333,-7.860656,2.628400,16,-4.549958,-4.649225,-6.423465,-6.290484,-6.807066,-5.744040,0.950231,0.049256,0.055930,-1.019837,0.007074,-0.514386,-0.284392,0.425645,16,0.180259,0.306919,0.407458,0.493556,0.447080,0.367054,0.111846
7,0.001631,0.001997,0.004039,0.003440,ball_tree,10,11,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.324469,-8.111599,-6.570455,-6.488354,-3.875891,-6.074154,1.411626,19,-3.741595,-4.082848,-4.796699,-4.855221,-5.325386,-4.560350,0.570343,-5.979051,-11.869517,-7.754560,-9.003960,-4.735069,-7.868432,2.477854,19,-4.592322,-4.856491,-6.890462,-6.441818,-6.918504,-5.939919,1.010237,0.054191,0.036659,-0.919289,0.092272,-0.937410,-0.334715,0.485067,22,0.164923,0.243745,0.318169,0.468895,0.428828,0.324912,0.112924
15,0.018858,0.030082,0.008777,0.008260,ball_tree,20,11,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.324469,-8.111599,-6.570455,-6.488354,-3.875891,-6.074154,1.411626,19,-3.741595,-4.082848,-4.796699,-4.855221,-5.325386,-4.560350,0.570343,-5.979051,-11.869517,-7.754560,-9.003960,-4.735069,-7.868432,2.477854,19,-4.592322,-4.856491,-6.890462,-6.441818,-6.918504,-5.939919,1.010237,0.054191,0.036659,-0.919289,0.092272,-0.937410,-0.334715,0.485067,22,0.164923,0.243745,0.318169,0.468895,0.428828,0.324912,0.112924
23,0.016167,0.007749,0.017412,0.026400,ball_tree,30,11,2,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.324469,-8.111599,-6.570455,-6.488354,-3.875891,-6.074154,1.411626,19,-3.741595,-4.082848,-4.796699,-4.855221,-5.325386,-4.560350,0.570343,-5.979051,-11.869517,-7.754560,-9.003960,-4.735069,-7.868432,2.477854,19,-4.592322,-4.856491,-6.890462,-6.441818,-6.918504,-5.939919,1.010237,0.054191,0.036659,-0.919289,0.092272,-0.937410,-0.334715,0.485067,22,0.164923,0.243745,0.318169,0.468895,0.428828,0.324912,0.112924
6,0.000000,0.000000,0.003232,0.004400,ball_tree,10,11,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.398389,-7.708726,-6.800774,-6.937015,-3.400620,-6.049105,1.519581,16,-4.077107,-3.930714,-4.537670,-4.273314,-4.872587,-4.338279,0.335792,-6.081164,-11.707965,-8.253882,-9.118393,-4.281986,-7.888678,2.549818,22,-4.931397,-4.691385,-6.855817,-5.789224,-6.689107,-5.791386,0.881874,0.021609,0.062704,-1.174415,0.069052,-0.584380,-0.321086,0.492836,19,0.037055,0.294292,0.325008,0.571053,0.466077,0.338697,0.180755
14,0.008473,0.007882,0.000926,0.001188,ball_tree,20,11,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.398389,-7.708726,-6.800774,-6.937015,-3.400620,-6.049105,1.519581,16,-4.077107,-3.930714,-4.537670,-4.273314,-4.872587,-4.338279,0.335792,-6.081164,-11.707965,-8.253882,-9.118393,-4.281986,-7.888678,2.549818,22,-4.931397,-4.691385,-6.855817,-5.789224,-6.689107,-5.791386,0.881874,0.021609,0.062704,-1.174415,0.069052,-0.584380,-0.321086,0.492836,19,0.037055,0.294292,0.325008,0.571053,0.466077,0.338697,0.180755
22,0.002403,0.004806,0.004249,0.003533,ball_tree,30,11,1,uniform,"{'knn__algorithm': 'ball_tree', 'knn__leaf_siz...",-5.398389,-7.708726,-6.800774,-6.937015,-3.400620,-6.049105,1.519581,16,-4.077107,-3.930714,-4.537670,-4.273314,-4.872587,-4.338279,0.335792,-6.081164,-11.707965,-8.253882,-9.118393,-4.281986,-7.888678,2.549818,22,-4.931397,-4.691385,-6.855817,-5.789224,-6.689107,-5.791386,0.881874,0.021609,0.062704,-1.174415,0.069052,-0.584380,-0.321086,0.492836,19,0.037055,0.294292,0.325008,0.571053,0.466077,0.338697,0.180755

In [69]:
pipeline = Pipeline([
    ('scaler', StandardScaler()), 
    ('rfr', RandomForestRegressor())
])

param_grid= {
    'rfr__n_estimators': [50, 100, 200, 300],
    'rfr__max_depth': [2, 6, 10, 20, None],
    'rfr__min_samples_split': [2, 5],
    'rfr__min_samples_leaf': [1, 2],
    'rfr__max_features': ['sqrt', 'log2',None]
}

model = GridSearchCV(
    pipeline,
    param_grid,
    cv=tscv,
    scoring=scoring,
    refit='RMSE',
)

model.fit(X, y)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('rfr', RandomForestRegressor())]),
             param_grid={'rfr__max_depth': [2, 6, 10, 20, None],
                         'rfr__max_features': ['sqrt', 'log2', None],
                         'rfr__min_samples_leaf': [1, 2],
                         'rfr__min_samples_split': [2, 5],
                         'rfr__n_estimators': [50, 100, 200, 300]},
             refit='RMSE',
             scoring={'MAE': 'neg_mean_absolute_error', 'R2': 'r2',
                      'RMSE': 'neg_root_mean_squared_error'})

In [70]:
pd.DataFrame(model.cv_results_).sort_values('rank_test_RMSE')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_rfr__max_depth,param_rfr__max_features,param_rfr__min_samples_leaf,param_rfr__min_samples_split,param_rfr__n_estimators,params,split0_test_MAE,split1_test_MAE,split2_test_MAE,split3_test_MAE,split4_test_MAE,mean_test_MAE,std_test_MAE,rank_test_MAE,split0_test_RMSE,split1_test_RMSE,split2_test_RMSE,split3_test_RMSE,split4_test_RMSE,mean_test_RMSE,std_test_RMSE,rank_test_RMSE,split0_test_R2,split1_test_R2,split2_test_R2,split3_test_R2,split4_test_R2,mean_test_R2,std_test_R2,rank_test_R2
90,0.158428,0.022335,0.006375,0.007808,6,None,2,2,200,"{'rfr__max_depth': 6, 'rfr__max_features': Non...",-4.079101,-5.697569,-4.078267,-4.971839,-2.410653,-4.247486,1.100761,4,-4.879600,-9.465290,-4.684509,-6.874514,-3.025937,-5.785970,2.207933,1,0.370048,0.387393,0.299587,0.470858,0.208796,0.347336,0.088149,1
92,0.035581,0.006045,0.005688,0.007047,6,None,2,5,50,"{'rfr__max_depth': 6, 'rfr__max_features': Non...",-4.039304,-5.553776,-3.933881,-4.969962,-2.573175,-4.214019,1.016639,1,-4.822301,-9.600050,-4.577668,-6.861148,-3.266894,-5.825612,2.210418,2,0.384756,0.369825,0.331172,0.472913,0.077770,0.327287,0.133111,2
238,0.188419,0.043234,0.010067,0.003115,None,None,2,5,200,"{'rfr__max_depth': None, 'rfr__max_features': ...",-4.285416,-5.658290,-4.180126,-4.916299,-2.599555,-4.327937,1.012617,6,-5.047302,-9.448708,-4.800865,-6.727682,-3.141310,-5.833174,2.135491,3,0.326004,0.389538,0.264360,0.493220,0.147311,0.324087,0.116370,3
237,0.098565,0.009346,0.007475,0.004687,None,None,2,5,100,"{'rfr__max_depth': None, 'rfr__max_features': ...",-4.447842,-5.522401,-3.689233,-5.048063,-2.517189,-4.244946,1.059435,3,-5.139670,-9.487590,-4.397224,-6.947358,-3.262901,-5.846949,2.179193,4,0.301109,0.384503,0.382861,0.459584,0.080024,0.321616,0.130789,5
233,0.097168,0.016247,0.007066,0.001217,None,None,2,2,100,"{'rfr__max_depth': None, 'rfr__max_features': ...",-3.927937,-5.428430,-4.490956,-4.993103,-2.350961,-4.238278,1.068489,2,-4.822003,-9.456664,-5.210277,-6.806300,-3.089131,-5.876875,2.145103,5,0.384832,0.388509,0.133542,0.481306,0.175404,0.312719,0.134407,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,0.042117,0.011509,0.007370,0.005520,10,None,1,2,50,"{'rfr__max_depth': 10, 'rfr__max_features': No...",-3.986246,-5.560439,-12.498178,-5.459338,-2.842888,-6.069418,3.367798,233,-4.875378,-9.264531,-13.829008,-7.269712,-3.674251,-7.782576,3.587442,236,0.371138,0.413104,-5.103910,0.408271,-0.166558,-0.815591,2.155309,239
129,0.091493,0.017929,0.005575,0.005910,10,None,1,2,100,"{'rfr__max_depth': 10, 'rfr__max_features': No...",-4.105124,-5.472930,-12.741118,-5.204353,-2.667026,-6.038110,3.494153,229,-4.855577,-9.244647,-14.048489,-7.447734,-3.334020,-7.786093,3.738137,237,0.376235,0.415621,-5.299198,0.378935,0.039483,-0.817785,2.244864,240
4,0.037254,0.004810,0.006617,0.003961,2,sqrt,1,5,50,"{'rfr__max_depth': 2, 'rfr__max_features': 'sq...",-4.698526,-7.500144,-9.720075,-7.103352,-2.234817,-6.251383,2.563640,238,-5.364347,-10.318383,-10.982653,-9.159944,-3.192005,-7.803466,3.016188,238,0.238670,0.271990,-2.849822,0.060549,0.119568,-0.431809,1.211453,230
116,0.050441,0.003303,0.007774,0.007268,10,log2,1,5,50,"{'rfr__max_depth': 10, 'rfr__max_features': 'l...",-4.421379,-7.608963,-10.987206,-7.062514,-2.777094,-6.571431,2.822638,239,-5.379564,-10.290246,-12.072183,-9.117688,-3.332848,-8.038506,3.216169,239,0.234345,0.275955,-3.651549,0.069196,0.040158,-0.606379,1.525307,237
0,0.052342,0.013789,0.010689,0.011327,2,sqrt,1,2,50,"{'rfr__max_depth': 2, 'rfr__max_features': 'sq...",-4.501926,-7.548477,-10.888258,-7.234028,-2.746497,-6.583837,2.790729,240,-5.215881,-10.528546,-11.955818,-9.151761,-3.599044,-8.090210,3.176402,240,0.280229,0.242032,-3.562308,0.062226,-0.119291,-0.619422,1.478298,238

In [75]:
pipeline = Pipeline([
    ('scaler', StandardScaler()), 
    ('enet', ElasticNet(max_iter=10000))
])

param_grid = {
    'enet__alpha': [0.01,0.1, 1, 10],
    'enet__l1_ratio': [0.1, 0.25, 0.5, 0.75]
}

model = GridSearchCV(
    pipeline,
    param_grid,
    cv=tscv,
    scoring=scoring,
    refit='RMSE'
)

model.fit(X, y)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('enet', ElasticNet(max_iter=10000))]),
             param_grid={'enet__alpha': [0.01, 0.1, 1, 10],
                         'enet__l1_ratio': [0.1, 0.25, 0.5, 0.75]},
             refit='RMSE',
             scoring={'MAE': 'neg_mean_absolute_error', 'R2': 'r2',
                      'RMSE': 'neg_root_mean_squared_error'})

In [76]:
pd.DataFrame(model.cv_results_).sort_values('rank_test_RMSE')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_enet__alpha,param_enet__l1_ratio,params,split0_test_MAE,split1_test_MAE,split2_test_MAE,split3_test_MAE,split4_test_MAE,mean_test_MAE,std_test_MAE,rank_test_MAE,split0_test_RMSE,split1_test_RMSE,split2_test_RMSE,split3_test_RMSE,split4_test_RMSE,mean_test_RMSE,std_test_RMSE,rank_test_RMSE,split0_test_R2,split1_test_R2,split2_test_R2,split3_test_R2,split4_test_R2,mean_test_R2,std_test_R2,rank_test_R2
3,0.003373,0.002965,0.003327,0.003162,0.01,0.75,"{'enet__alpha': 0.01, 'enet__l1_ratio': 0.75}",-0.136866,-0.212935,-0.101395,-0.351366,-0.121889,-0.184890,0.091376,1,-0.159980,-0.296920,-0.131572,-0.472763,-0.143723,-0.240991,0.130263,1,0.999323,0.999397,0.999447,0.997497,0.998215,0.998776,0.000785,1
2,0.005654,0.003385,0.002084,0.003166,0.01,0.50,"{'enet__alpha': 0.01, 'enet__l1_ratio': 0.5}",-0.243399,-0.346430,-0.171848,-0.605251,-0.216306,-0.316647,0.155293,2,-0.288636,-0.474135,-0.221022,-0.826160,-0.255408,-0.413072,0.224319,2,0.997796,0.998463,0.998441,0.992358,0.994363,0.996284,0.002482,2
1,0.006668,0.002016,0.002656,0.002245,0.01,0.25,"{'enet__alpha': 0.01, 'enet__l1_ratio': 0.25}",-0.355350,-0.472626,-0.240402,-0.840753,-0.304483,-0.442723,0.213073,3,-0.420323,-0.642659,-0.307862,-1.155140,-0.360078,-0.577212,0.310675,3,0.995326,0.997176,0.996975,0.985060,0.988796,0.992667,0.004875,3
0,0.005582,0.002604,0.005548,0.003154,0.01,0.10,"{'enet__alpha': 0.01, 'enet__l1_ratio': 0.1}",-0.419724,-0.547215,-0.280837,-0.974504,-0.355019,-0.515460,0.245636,4,-0.497349,-0.741884,-0.358825,-1.342548,-0.420208,-0.672163,0.359583,4,0.993456,0.996237,0.995890,0.979819,0.984742,0.990029,0.006585,4
7,0.000000,0.000000,0.006565,0.003287,0.10,0.75,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.75}",-1.105055,-1.723348,-0.871907,-2.558525,-0.936175,-1.439002,0.635631,5,-1.291380,-2.427282,-1.114343,-3.437115,-1.112137,-1.876452,0.921562,5,0.955879,0.959714,0.960366,0.867725,0.893123,0.927361,0.039187,5
6,0.004716,0.003859,0.003299,0.004040,0.10,0.50,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.5}",-1.671539,-2.395392,-1.300810,-3.531610,-1.370523,-2.053975,0.834337,6,-1.987803,-3.309978,-1.634626,-4.842507,-1.630988,-2.681180,1.244642,6,0.895459,0.925086,0.914717,0.737440,0.770136,0.848568,0.078652,6
5,0.000936,0.001165,0.004081,0.003959,0.10,0.25,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.25}",-2.136011,-2.880050,-1.623448,-4.120644,-1.646652,-2.481361,0.937893,7,-2.532136,-3.949923,-2.018430,-5.729625,-1.968997,-3.239822,1.436035,7,0.830366,0.893318,0.869967,0.632429,0.664989,0.778214,0.108130,7
4,0.004871,0.003326,0.003300,0.003109,0.10,0.10,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.1}",-2.365243,-3.112395,-1.779199,-4.369448,-1.767654,-2.678788,0.978170,8,-2.803194,-4.257202,-2.201416,-6.118552,-2.120642,-3.500201,1.516882,8,0.792104,0.876074,0.845321,0.580834,0.611399,0.741147,0.121810,8
11,0.004866,0.003973,0.003320,0.004069,1.00,0.75,"{'enet__alpha': 1, 'enet__l1_ratio': 0.75}",-3.851916,-5.599253,-3.425738,-5.865548,-2.364700,-4.221431,1.328054,9,-4.343268,-8.392122,-4.057281,-7.861658,-3.207716,-5.572409,2.125541,9,0.500918,0.518432,0.474593,0.307983,0.110879,0.382561,0.155121,9
10,0.007650,0.001230,0.002203,0.003135,1.00,0.50,"{'enet__alpha': 1, 'enet__l1_ratio': 0.5}",-4.118599,-6.141056,-3.527391,-6.331741,-2.473515,-4.518461,1.499648,10,-4.630822,-8.743543,-4.271896,-8.480346,-3.303209,-5.885963,2.269264,10,0.432645,0.477256,0.417538,0.194778,0.057153,0.315874,0.162244,10
9,0.004872,0.003979,0.001606,0.003211,1.00,0.25,"{'enet__alpha': 1, 'enet__l1_ratio': 0.25}",-4.258564,-6.465261,-3.683040,-6.532507,-2.579372,-4.703749,1.562069,11,-4.872731,-9.012610,-4.532571,-8.764727,-3.423540,-6.121236,2.311202,11,0.371820,0.444588,0.344285,0.139867,-0.012791,0.257554,0.168818,11
8,0.004851,0.003961,0.003212,0.003934,1.00,0.10,"{'enet__alpha': 1, 'enet__l1_ratio': 0.1}",-4.294656,-6.594735,-3.763099,-6.600235,-2.632875,-4.777120,1.580270,12,-4.960880,-9.101202,-4.626043,-8.861695,-3.474446,-6.204853,2.321331,12,0.348887,0.433615,0.316961,0.120730,-0.043134,0.235412,0.172946,12
12,0.007414,0.004126,0.000000,0.000000,10.00,0.10,"{'enet__alpha': 10, 'enet__l1_ratio': 0.1}",-5.289951,-8.045055,-8.199030,-6.859985,-6.212939,-6.921392,1.101113,13,-5.925427,-12.003340,-9.472317,-9.741629,-7.038920,-8.836326,2.142804,13,0.071080,0.014814,-1.863772,-0.062556,-3.281352,-1.024357,1.341907,13
13,0.003221,0.003945,0.003245,0.003974,10.00,0.25,"{'enet__alpha': 10, 'enet__l1_ratio': 0.25}",-5.397746,-8.091765,-8.813029,-7.138461,-6.819378,-7.252076,1.164502,14,-6.170547,-12.352898,-10.130842,-9.923943,-7.585442,-9.232735,2.149900,14,-0.007364,-0.043402,-2.275798,-0.102699,-3.971995,-1.280252,1.598328,14
14,0.004909,0.004010,0.003303,0.004048,10.00,0.50,"{'enet__alpha': 10, 'enet__l1_ratio': 0.5}",-5.422306,-8.151268,-9.541330,-7.751298,-7.802842,-7.733809,1.325860,15,-6.194817,-12.490842,-10.969822,-10.407044,-8.495092,-9.711523,2.174332,15,-0.015303,-0.066835,-2.840831,-0.212672,-5.235986,-1.674326,2.074559,15
15,0.003274,0.004011,0.003277,0.004015,10.00,0.75,"{'enet__alpha': 10, 'enet__l1_ratio': 0.75}",-5.422306,-8.151268,-9.848721,-7.884695,-8.082433,-7.877885,1.416382,16,-6.194817,-12.490842,-11.328207,-10.572209,-8.769169,-9.871049,2.200322,16,-0.015303,-0.066835,-3.095891,-0.251469,-5.644860,-1.814872,2.238219,16