In [89]:
%pip install selenium-stealth

Collecting selenium-stealth
  Downloading selenium_stealth-1.0.6-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: selenium in d:\anaconda\envs\tf2.10\lib\site-packages (from selenium-stealth) (4.38.0)
Requirement already satisfied: urllib3<3.0,>=2.5.0 in d:\anaconda\envs\tf2.10\lib\site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium->selenium-stealth) (2.5.0)
Requirement already satisfied: trio<1.0,>=0.31.0 in d:\anaconda\envs\tf2.10\lib\site-packages (from selenium->selenium-stealth) (0.32.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in d:\anaconda\envs\tf2.10\lib\site-packages (from selenium->selenium-stealth) (0.12.2)
Requirement already satisfied: certifi>=2025.10.5 in d:\anaconda\envs\tf2.10\lib\site-packages (from selenium->selenium-stealth) (2025.11.12)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in d:\anaconda\envs\tf2.10\lib\site-packages (from selenium->selenium-stealth) (4.15.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in d:\anaconda\envs\tf2.10\lib\site-packages (from selenium->selenium-stealth) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in d:\anaconda\envs\tf2.10\lib\site-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (25.3.0)
Requirement already satisfied: sortedcontainers in d:\anaconda\envs\tf2.10\lib\site-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (2.4.0)
Requirement already satisfied: idna in d:\anaconda\envs\tf2.10\lib\site-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (3.10)
Requirement already satisfied: outcome in d:\anaconda\envs\tf2.10\lib\site-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in d:\anaconda\envs\tf2.10\lib\site-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (1.3.1)
Requirement already satisfied: cffi>=1.14 in d:\anaconda\envs\tf2.10\lib\site-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (2.0.0)
Requirement already satisfied: exceptiongroup in d:\anaconda\envs\tf2.10\lib\site-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (1.3.0)
Requirement already satisfied: wsproto>=0.14 in d:\anaconda\envs\tf2.10\lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium->selenium-stealth) (1.3.1)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in d:\anaconda\envs\tf2.10\lib\site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium->selenium-stealth) (1.7.1)
Requirement already satisfied: pycparser in d:\anaconda\envs\tf2.10\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium->selenium-stealth) (2.23)
Requirement already satisfied: h11<1,>=0.16.0 in d:\anaconda\envs\tf2.10\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium->selenium-stealth) (0.16.0)
Downloading selenium_stealth-1.0.6-py3-none-any.whl (32 kB)
Installing collected packages: selenium-stealth
Successfully installed selenium-stealth-1.0.6
Note: you may need to restart the kernel to use updated packages.

In [2]:
import urllib.request
import requests
import bs4
from bs4 import BeautifulSoup
import time
import random
import undetected_chromedriver as uc
import pandas as pd
import numpy as np

In [2]:
driver = uc.Chrome()

driver.get("https://gizmodo.com/latest/page/2750")

time.sleep(5)
html = driver.page_source

In [28]:
html

'<html lang="en-US" class="dark"><head><script type="text/javascript" async="" src="https://cdn.id5-sync.com/api/1.0/id5PrebidModule.js"></script>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    <link rel="icon" type="image/png" href="/favicon.png?v1" sizes="96x96">\n    <link rel="icon" type="image/svg+xml" href="/favicon.svg?v1">\n    <link rel="shortcut icon" href="/favicon.ico?v1">\n    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v1">\n    <link rel="manifest" href="/site.webmanifest">\n    <link rel="mask-icon" href="/safari-pinned-tab.svg?v1" color="#004fff">\n    <meta name="apple-mobile-web-app-title" content="Gizmodo">\n    <meta name="application-name" content="Gizmodo">\n    <meta name="msapplication-TileColor" content="#004fff">\n    <meta name="theme-color" content="#ffffff">\n    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">\n    <link rel="preload" as="script" href="https://securepubads.g.doubleclick.net/tag/js/gpt.js"><link rel="preload" as="script" href="https://scripts.opti-digital.com/tags/?lib=corev2_c&amp;site=gizmodo"><link rel="preload" as="script" href="//scripts.opti-digital.com/lib/?lib=odpbjs&amp;v=9.35.0_ext"><link rel="preload" as="script" href="//c.amazon-adsystem.com/aax2/apstag.js"><script async="" src="//c.amazon-adsystem.com/aax2/apstag.js"></script><script async="" type="text/javascript" src="https://scripts.opti-digital.com/lib/?lib=odpbjs&amp;v=9.35.0_ext"></script><script async="" type="text/javascript" src="https://scripts.opti-digital.com/tags/?lib=corev2_c&amp;site=gizmodo"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-EYNXLD4983&amp;cx=c&amp;gtm=4e5bc1"></script><script async="" type="text/javascript" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-W5PBFP3X"></script><script src="https://sdk.mrf.io/statics/marfeel-sdk.es5.js?id=6017" async="" type="text/javascript" nomodule=""></script><script src="https://sdk.mrf.io/statics/marfeel-sdk.js?id=6017" type="module"></script><script>window.iconPath = "https://gizmodo.com/app/themes/gizmodo/public/images/icons.svg?v2";</script>\n    <script>(function e(){try{if("theme"in localStorage)return"dark"===localStorage.theme;return window.matchMedia("(prefers-color-scheme: dark)").matches}catch{return window.matchMedia("(prefers-color-scheme: dark)").matches}})()&&!window.matchMedia("print").matches?document.documentElement.classList.add("dark"):document.documentElement.classList.remove("dark");</script>\n    <style>.dark .dark\\:bg-main-950,.dark body{background-color:#030314}</style>\n    <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">\n\n\t<!-- This site is optimized with the Yoast SEO plugin v22.9 - https://yoast.com/wordpress/plugins/seo/ -->\n\t<title>Latest | Page 2750 of 17869</title>\n\t<link rel="canonical" href="https://gizmodo.com/latest/page/2750">\n\t<link rel="prev" href="https://gizmodo.com/latest/page/2749">\n\t<link rel="next" href="https://gizmodo.com/latest/page/2751">\n\t<meta property="og:locale" content="en_US">\n\t<meta property="og:type" content="article">\n\t<meta property="og:title" content="Latest | Page 2750 of 17869">\n\t<meta property="og:url" content="https://gizmodo.com/latest">\n\t<meta property="og:site_name" content="Gizmodo">\n\t<meta property="og:image" content="https://gizmodo.com/app/uploads/2025/10/gizmodo-social-1200x675-1.jpg">\n\t<meta property="og:image:width" content="1200">\n\t<meta property="og:image:height" content="675">\n\t<meta property="og:image:type" content="image/jpeg">\n\t<meta name="twitter:card" content="summary_large_image">\n\t<meta name="twitter:site" content="@Gizmodo">\n\t<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":["WebPage","CollectionPage"],"@id":"https://gizmodo.com/latest","url":"https://gizmodo.com/latest/page/2750","name":"Latest | Page 2750 of 17869","isPartOf":{"@id":"https://gizmodo.com/#website"},"datePublished":"2024-06-28T15:42:01+00:00","dateModified":"2024-07-08T13:55:45+00:00","inLanguage":"en-US"},{"@type":"WebSite","@id":"https://gizmodo.com/#website","url":"https://gizmodo.com/","name":"Gizmodo","description":"The Future Is Here","publisher":{"@id":"https://gizmodo.com/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://gizmodo.com/?s={search_term_string}"},"query-input":"required name=search_term_string"}],"inLanguage":"en-US"},{"@type":"Organization","@id":"https://gizmodo.com/#organization","name":"Gizmodo","url":"https://gizmodo.com/","logo":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://gizmodo.com/#/schema/logo/image/","url":"https://gizmodo.com/app/uploads/2025/10/gizmodo-identity-696x696-1.jpg","contentUrl":"https://gizmodo.com/app/uploads/2025/10/gizmodo-identity-696x696-1.jpg","width":696,"height":696,"caption":"Gizmodo"},"image":{"@id":"https://gizmodo.com/#/schema/logo/image/"},"sameAs":["https://www.facebook.com/gizmodo/","https://x.com/Gizmodo"]}]}</script>\n\t<!-- / Yoast SEO plugin. -->\n\n\n<link rel="dns-prefetch" href="//api.consentframework.com">\n<link rel="dns-prefetch" href="//cache.consentframework.com">\n<link rel="dns-prefetch" href="//scripts.opti-digital.com">\n\n<link rel="alternate" type="application/rss+xml" href="https://gizmodo.com/feed">\n<meta property="mrf:tags" content="contentType:Home">\n\n<script type="text/javascript" src="https://cache.consentframework.com/js/pa/41707/c/V2Sw7/stub" charset="utf-8"></script>\n<script type="text/javascript" src="https://cdn.sirdata.eu/youtube-iframe.js"></script>\n<script type="text/javascript" src="https://cache.consentframework.com/js/pa/41707/c/V2Sw7/cmp" charset="utf-8" async=""></script>\n<script type="text/javascript">\n!function(){"use strict";function e(e){var t=!(arguments.length>1&&void 0!==arguments[1])||arguments[1],c=document.createElement("script");c.src=e,t?c.type="module":(c.async=!0,c.type="text/javascript",c.setAttribute("nomodule",""));var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(c,n)}!function(t,c){!function(t,c,n){var a,o,r;n.accountId=c,null!==(a=t.marfeel)&&void 0!==a||(t.marfeel={}),null!==(o=(r=t.marfeel).cmd)&&void 0!==o||(r.cmd=[]),t.marfeel.config=n;var i="https://sdk.mrf.io/statics";e("".concat(i,"/marfeel-sdk.js?id=").concat(c),!0),e("".concat(i,"/marfeel-sdk.es5.js?id=").concat(c),!1)}(t,c,arguments.length>2&&void 0!==arguments[2]?arguments[2]:{})}(window,6017,{} /* Config */)}();\n</script>\n<script type="text/javascript">\nwindow[\'gtag_enable_tcf_support\'] = true;\n(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\n    new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\n    j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n    \'https://www.googletagmanager.com/gtm.js?id=\'+i+dl+\'\';f.parentNode.insertBefore(j,f);\n})(window,document,\'script\',\'dataLayer\',\'GTM-W5PBFP3X\');\n</script>\n<link rel="preload" href="https://securepubads.g.doubleclick.net/tag/js/gpt.js" as="script" type="text/javascript">\n<script>var optidigitalQueue = optidigitalQueue || {}; optidigitalQueue.cmd = optidigitalQueue.cmd || [];</script>\n<script type="module" id="optidigital-ad-init" async="" data-config="{&quot;adUnit&quot;:&quot;/23178111854/od.gizmodo.com/home&quot;,&quot;pageTargeting&quot;:{&quot;post_id&quot;:&quot;&quot;,&quot;nop&quot;:&quot;0&quot;,&quot;nos&quot;:&quot;0&quot;,&quot;tags&quot;:[],&quot;environment&quot;:&quot;&quot;}}" src="//scripts.opti-digital.com/modules/?site=gizmodo"></script>\n<script>!function(n){if(!window.cnx){window.cnx={},window.cnx.cmd=[];var t=n.createElement(\'iframe\');t.src=\'javascript:false\'; t.display=\'none\',t.onload=function(){var n=t.contentWindow.document,c=n.createElement(\'script\');c.src=\'//cd.connatix.com/connatix.player.js?cid=872d12ce-453b-4870-845f-955919887e1b&pid=92b7b46b-43ed-4e0e-b21b-2c999302d9d7\',c.setAttribute(\'async\',\'1\'),c.setAttribute(\'type\',\'text/javascript\'),n.body.appendChild(c)},n.head.appendChild(t)}}(document);</script><iframe src="javascript:false" data-cnx-ids="8768116cbec34df38a0715307c45147c"></iframe><link rel="stylesheet" href="https://gizmodo.com/app/plugins/pdfjs-viewer-shortcode/inc/../blocks/dist/style.css?ver=2.2.1"><link rel="stylesheet" href="https://gizmodo.com/app/plugins/keleops-shopbot/css/all.min.css?ver=1.6.33"><link rel="stylesheet" href="https://gizmodo.com/app/plugins/keleops-toc/assets/css/screen.min.css?ver=2.0.23"><style id="ez-toc-inline-css">\ndiv#ez-toc-container p.ez-toc-title {font-size: 120%;}div#ez-toc-container p.ez-toc-title {font-weight: 500;}div#ez-toc-container ul li {font-size: 100%;}div#ez-toc-container {width: 100%;}\n</style>\n<link rel="stylesheet" href="https://gizmodo.com/app/plugins/simple-tags/assets/frontend/css/frontend.css?ver=3.26.0"><link rel="stylesheet" href="https://gizmodo.com/app/themes/gizmodo/public/app.765203.css"><style id="rocket-lazyload-inline-css">\n.rll-youtube-player{position:relative;padding-bottom:56.23%;height:0;overflow:hidden;max-width:100%;}.rll-youtube-player:focus-within{outline: 2px solid currentColor;outline-offset: 5px;}.rll-youtube-player iframe{position:absolute;top:0;left:0;width:100%;height:100%;z-index:100;background:0 0}.rll-youtube-player img{bottom:0;display:block;left:0;margin:auto;max-width:100%;width:100%;position:absolute;right:0;top:0;border:none;height:auto;-webkit-transition:.4s all;-moz-transition:.4s all;transition:.4s all}.rll-youtube-player img:hover{-webkit-filter:brightness(75%)}.rll-youtube-player .play{height:100%;width:100%;left:0;top:0;position:absolute;background:url(https://gizmodo.com/app/plugins/wp-rocket/assets/img/youtube.png) no-repeat center;background-color: transparent !important;cursor:pointer;border:none;}.wp-embed-responsive .wp-has-aspect-ratio .rll-youtube-player{position:absolute;padding-bottom:0;width:100%;height:100%;top:0;bottom:0;left:0;right:0}\n</style>\n<script type="text/javascript">\n            window._nslDOMReady = function (callback) {\n                if ( document.readyState === "complete" || document.readyState === "interactive" ) {\n                    callback();\n                } else {\n                    document.addEventListener( "DOMContentLoaded", callback );\n                }\n            };\n            </script><script src="https://gizmodo.com/wp/wp-includes/js/jquery/jquery.min.js?ver=3.7.1"></script><script src="https://gizmodo.com/wp/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.1"></script><script src="https://gizmodo.com/app/plugins/simple-tags/assets/frontend/js/frontend.js?ver=3.26.0"></script><noscript>\n  <img src="https://sb.scorecardresearch.com/p?c1=2&amp;c2=39636245&amp;cv=3.9.1&amp;cj=1">\n</noscript>\n<style type="text/css">div.nsl-container[data-align="left"] {\n    text-align: left;\n}\n\ndiv.nsl-container[data-align="center"] {\n    text-align: center;\n}\n\ndiv.nsl-container[data-align="right"] {\n    text-align: right;\n}\n\n\ndiv.nsl-container div.nsl-container-buttons a[data-plugin="nsl"] {\n    text-decoration: none;\n    box-shadow: none;\n    border: 0;\n}\n\ndiv.nsl-container .nsl-container-buttons {\n    display: flex;\n    padding: 5px 0;\n}\n\ndiv.nsl-container.nsl-container-block .nsl-container-buttons {\n    display: inline-grid;\n    grid-template-columns: minmax(145px, auto);\n}\n\ndiv.nsl-container-block-fullwidth .nsl-container-buttons {\n    flex-flow: column;\n    align-items: center;\n}\n\ndiv.nsl-container-block-fullwidth .nsl-container-buttons a,\ndiv.nsl-container-block .nsl-container-buttons a {\n    flex: 1 1 auto;\n    display: block;\n    margin: 5px 0;\n    width: 100%;\n}\n\ndiv.nsl-container-inline {\n    margin: -5px;\n    text-align: left;\n}\n\ndiv.nsl-container-inline .nsl-container-buttons {\n    justify-content: center;\n    flex-wrap: wrap;\n}\n\ndiv.nsl-container-inline .nsl-container-buttons a {\n    margin: 5px;\n    display: inline-block;\n}\n\ndiv.nsl-container-grid .nsl-container-buttons {\n    flex-flow: row;\n    align-items: center;\n    flex-wrap: wrap;\n}\n\ndiv.nsl-container-grid .nsl-container-buttons a {\n    flex: 1 1 auto;\n    display: block;\n    margin: 5px;\n    max-width: 280px;\n    width: 100%;\n}\n\n@media only screen and (min-width: 650px) {\n    div.nsl-container-grid .nsl-container-buttons a {\n        width: auto;\n    }\n}\n\ndiv.nsl-container .nsl-button {\n    cursor: pointer;\n    vertical-align: top;\n    border-radius: 4px;\n}\n\ndiv.nsl-container .nsl-button-default {\n    color: #fff;\n    display: flex;\n}\n\ndiv.nsl-container .nsl-button-icon {\n    display: inline-block;\n}\n\ndiv.nsl-container .nsl-button-svg-container {\n    flex: 0 0 auto;\n    padding: 8px;\n    display: flex;\n    align-items: center;\n}\n\ndiv.nsl-container svg {\n    height: 24px;\n    width: 24px;\n    vertical-align: top;\n}\n\ndiv.nsl-container .nsl-button-default div.nsl-button-label-container {\n    margin: 0 24px 0 12px;\n    padding: 10px 0;\n    font-family: Helvetica, Arial, sans-serif;\n    font-size: 16px;\n    line-height: 20px;\n    letter-spacing: .25px;\n    overflow: hidden;\n    text-align: center;\n    text-overflow: clip;\n    white-space: nowrap;\n    flex: 1 1 auto;\n    -webkit-font-smoothing: antialiased;\n    -moz-osx-font-smoothing: grayscale;\n    text-transform: none;\n    display: inline-block;\n}\n\ndiv.nsl-container .nsl-button-google[data-skin="dark"] .nsl-button-svg-container {\n    margin: 1px;\n    padding: 7px;\n    border-radius: 3px;\n    background: #fff;\n}\n\ndiv.nsl-container .nsl-button-google[data-skin="light"] {\n    border-radius: 1px;\n    box-shadow: 0 1px 5px 0 rgba(0, 0, 0, .25);\n    color: RGBA(0, 0, 0, 0.54);\n}\n\ndiv.nsl-container .nsl-button-apple .nsl-button-svg-container {\n    padding: 0 6px;\n}\n\ndiv.nsl-container .nsl-button-apple .nsl-button-svg-container svg {\n    height: 40px;\n    width: auto;\n}\n\ndiv.nsl-container .nsl-button-apple[data-skin="light"] {\n    color: #000;\n    box-shadow: 0 0 0 1px #000;\n}\n\ndiv.nsl-container .nsl-button-facebook[data-skin="white"] {\n    color: #000;\n    box-shadow: inset 0 0 0 1px #000;\n}\n\ndiv.nsl-container .nsl-button-facebook[data-skin="light"] {\n    color: #1877F2;\n    box-shadow: inset 0 0 0 1px #1877F2;\n}\n\ndiv.nsl-container .nsl-button-spotify[data-skin="white"] {\n    color: #191414;\n    box-shadow: inset 0 0 0 1px #191414;\n}\n\ndiv.nsl-container .nsl-button-apple div.nsl-button-label-container {\n    font-size: 17px;\n    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";\n}\n\ndiv.nsl-container .nsl-button-slack div.nsl-button-label-container {\n    font-size: 17px;\n    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";\n}\n\ndiv.nsl-container .nsl-button-slack[data-skin="light"] {\n    color: #000000;\n    box-shadow: inset 0 0 0 1px #DDDDDD;\n}\n\ndiv.nsl-container .nsl-button-tiktok[data-skin="light"] {\n    color: #161823;\n    box-shadow: 0 0 0 1px rgba(22, 24, 35, 0.12);\n}\n\n\ndiv.nsl-container .nsl-button-kakao {\n    color: rgba(0, 0, 0, 0.85);\n}\n\n.nsl-clear {\n    clear: both;\n}\n\n.nsl-container {\n    clear: both;\n}\n\n.nsl-disabled-provider .nsl-button {\n    filter: grayscale(1);\n    opacity: 0.8;\n}\n\n/*Button align start*/\n\ndiv.nsl-container-inline[data-align="left"] .nsl-container-buttons {\n    justify-content: flex-start;\n}\n\ndiv.nsl-container-inline[data-align="center"] .nsl-container-buttons {\n    justify-content: center;\n}\n\ndiv.nsl-container-inline[data-align="right"] .nsl-container-buttons {\n    justify-content: flex-end;\n}\n\n\ndiv.nsl-container-grid[data-align="left"] .nsl-container-buttons {\n    justify-content: flex-start;\n}\n\ndiv.nsl-container-grid[data-align="center"] .nsl-container-buttons {\n    justify-content: center;\n}\n\ndiv.nsl-container-grid[data-align="right"] .nsl-container-buttons {\n    justify-content: flex-end;\n}\n\ndiv.nsl-container-grid[data-align="space-around"] .nsl-container-buttons {\n    justify-content: space-around;\n}\n\ndiv.nsl-container-grid[data-align="space-between"] .nsl-container-buttons {\n    justify-content: space-between;\n}\n\n/* Button align end*/\n\n/* Redirect */\n\n#nsl-redirect-overlay {\n    display: flex;\n    flex-direction: column;\n    justify-content: center;\n    align-items: center;\n    position: fixed;\n    z-index: 1000000;\n    left: 0;\n    top: 0;\n    width: 100%;\n    height: 100%;\n    backdrop-filter: blur(1px);\n    background-color: RGBA(0, 0, 0, .32);;\n}\n\n#nsl-redirect-overlay-container {\n    display: flex;\n    flex-direction: column;\n    justify-content: center;\n    align-items: center;\n    background-color: white;\n    padding: 30px;\n    border-radius: 10px;\n}\n\n#nsl-redirect-overlay-spinner {\n    content: \'\';\n    display: block;\n    margin: 20px;\n    border: 9px solid RGBA(0, 0, 0, .6);\n    border-top: 9px solid #fff;\n    border-radius: 50%;\n    box-shadow: inset 0 0 0 1px RGBA(0, 0, 0, .6), 0 0 0 1px RGBA(0, 0, 0, .6);\n    width: 40px;\n    height: 40px;\n    animation: nsl-loader-spin 2s linear infinite;\n}\n\n@keyframes nsl-loader-spin {\n    0% {\n        transform: rotate(0deg)\n    }\n    to {\n        transform: rotate(360deg)\n    }\n}\n\n#nsl-redirect-overlay-title {\n    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;\n    font-size: 18px;\n    font-weight: bold;\n    color: #3C434A;\n}\n\n#nsl-redirect-overlay-text {\n    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;\n    text-align: center;\n    font-size: 14px;\n    color: #3C434A;\n}\n\n/* Redirect END*/</style><style type="text/css">/* Notice fallback */\n#nsl-notices-fallback {\n    position: fixed;\n    right: 10px;\n    top: 10px;\n    z-index: 10000;\n}\n\n.admin-bar #nsl-notices-fallback {\n    top: 42px;\n}\n\n#nsl-notices-fallback > div {\n    position: relative;\n    background: #fff;\n    border-left: 4px solid #fff;\n    box-shadow: 0 1px 1px 0 rgba(0, 0, 0, .1);\n    margin: 5px 15px 2px;\n    padding: 1px 20px;\n}\n\n#nsl-notices-fallback > div.error {\n    display: block;\n    border-left-color: #dc3232;\n}\n\n#nsl-notices-fallback > div.updated {\n    display: block;\n    border-left-color: #46b450;\n}\n\n#nsl-notices-fallback p {\n    margin: .5em 0;\n    padding: 2px;\n}\n\n#nsl-notices-fallback > div:after {\n    position: absolute;\n    right: 5px;\n    top: 5px;\n    content: \'\\00d7\';\n    display: block;\n    height: 16px;\n    width: 16px;\n    line-height: 16px;\n    text-align: center;\n    font-size: 20px;\n    cursor: pointer;\n}</style><script>!(function(o,u,s){function f(t,n,e){k?S(t,n):((e=e===s?f.lazy:e)?N:C).push(t,Math.max(e?350:0,n))}function i(t){j.head.appendChild(t)}function a(t,n){t.forEach(function(t){n(t)})}function r(n,t,e,c){a(t.split(" "),function(t){(c||o)[n+"EventListener"](t,e||p)})}function l(t,n,e,c){return(c=n?j.getElementById(n):s)||(c=j.createElement(t),n&&(c.id=n)),e&&r(g,b,e,c),c}function d(t,n){a(q.call(t.attributes),function(t){n(t.name,t.value)})}function h(t,n){return q.call((n||j).querySelectorAll(t))}function m(c,t){a(h("source,img",c),m),d(c,function(t,n,e){(e=/^data-(.+)/.exec(t))&&c[x](e[1],n)}),t&&(c.className+=" "+t),c[b]&&c[b]()}function t(t,n,e){f(function(n){a(n=h(t||"script[type=deferjs]"),function(t,e){t.src&&(e=l(v),d(t,function(t

In [11]:
links = []

In [12]:
for i in range(1, 2751):
    url = f"https://gizmodo.com/latest/page/{i}"
    print(f"Scraping: {url} links:{len(links)}")

    try:
        driver.get(url)
        time.sleep(random.uniform(2.5, 6.0)) 
        html = driver.page_source

        if "Just a moment" in html:
            print("Cloudflare challenge detected. Waiting...")
            time.sleep(10)
            html = driver.page_source
            if "Just a moment" in html:
                print("Still blocked. Skipping page.")
                continue
        
        soup = BeautifulSoup(html, "html.parser")

        articles = soup.select("div.mb-5.pb-5.border-b-0\\.5")  # each article container
        
        for article in articles:
            urls = article.select("div.h-full.w-full.md\\:w-2\\/3.flex.flex-col.gap-4.md\\:gap-0.justify-between a.block")
            for url in urls:
                links.append(url.get("href"))

        
    except Exception as e:
        print("Error:", e)
        time.sleep(10)
        continue

Scraping: https://gizmodo.com/latest/page/1 links:0
Scraping: https://gizmodo.com/latest/page/2 links:20
Scraping: https://gizmodo.com/latest/page/3 links:40
Scraping: https://gizmodo.com/latest/page/4 links:60
Scraping: https://gizmodo.com/latest/page/5 links:80
Scraping: https://gizmodo.com/latest/page/6 links:100
Scraping: https://gizmodo.com/latest/page/7 links:120
Scraping: https://gizmodo.com/latest/page/8 links:140
Scraping: https://gizmodo.com/latest/page/9 links:160
Scraping: https://gizmodo.com/latest/page/10 links:180
Scraping: https://gizmodo.com/latest/page/11 links:200
Scraping: https://gizmodo.com/latest/page/12 links:220
Scraping: https://gizmodo.com/latest/page/13 links:240
Scraping: https://gizmodo.com/latest/page/14 links:260
Scraping: https://gizmodo.com/latest/page/15 links:280
Scraping: https://gizmodo.com/latest/page/16 links:300
Scraping: https://gizmodo.com/latest/page/17 links:320
Scraping: https://gizmodo.com/latest/page/18 links:340
Scraping: https://gizmodo.com/latest/page/19 links:360
Scraping: https://gizmodo.com/latest/page/20 links:380
Scraping: https://gizmodo.com/latest/page/21 links:400
Scraping: https://gizmodo.com/latest/page/22 links:420
Scraping: https://gizmodo.com/latest/page/23 links:440
Scraping: https://gizmodo.com/latest/page/24 links:460
Scraping: https://gizmodo.com/latest/page/25 links:480
Scraping: https://gizmodo.com/latest/page/26 links:500
Scraping: https://gizmodo.com/latest/page/27 links:520
Scraping: https://gizmodo.com/latest/page/28 links:540
Scraping: https://gizmodo.com/latest/page/29 links:560
Scraping: https://gizmodo.com/latest/page/30 links:580
Scraping: https://gizmodo.com/latest/page/31 links:600
Scraping: https://gizmodo.com/latest/page/32 links:620
Scraping: https://gizmodo.com/latest/page/33 links:640
Scraping: https://gizmodo.com/latest/page/34 links:660
Scraping: https://gizmodo.com/latest/page/35 links:680
Scraping: https://gizmodo.com/latest/page/36 links:700
Scraping: https://gizmodo.com/latest/page/37 links:720
Scraping: https://gizmodo.com/latest/page/38 links:740
Scraping: https://gizmodo.com/latest/page/39 links:760
Scraping: https://gizmodo.com/latest/page/40 links:780
Scraping: https://gizmodo.com/latest/page/41 links:800
Scraping: https://gizmodo.com/latest/page/42 links:820
Scraping: https://gizmodo.com/latest/page/43 links:840
Scraping: https://gizmodo.com/latest/page/44 links:860
Scraping: https://gizmodo.com/latest/page/45 links:880
Scraping: https://gizmodo.com/latest/page/46 links:900
Scraping: https://gizmodo.com/latest/page/47 links:920
Scraping: https://gizmodo.com/latest/page/48 links:940
Scraping: https://gizmodo.com/latest/page/49 links:960
Scraping: https://gizmodo.com/latest/page/50 links:980
Scraping: https://gizmodo.com/latest/page/51 links:1000
Scraping: https://gizmodo.com/latest/page/52 links:1020
Scraping: https://gizmodo.com/latest/page/53 links:1040
Scraping: https://gizmodo.com/latest/page/54 links:1060
Scraping: https://gizmodo.com/latest/page/55 links:1080
Scraping: https://gizmodo.com/latest/page/56 links:1100
Scraping: https://gizmodo.com/latest/page/57 links:1120
Scraping: https://gizmodo.com/latest/page/58 links:1140
Scraping: https://gizmodo.com/latest/page/59 links:1160
Scraping: https://gizmodo.com/latest/page/60 links:1180
Scraping: https://gizmodo.com/latest/page/61 links:1200
Scraping: https://gizmodo.com/latest/page/62 links:1220
Scraping: https://gizmodo.com/latest/page/63 links:1240
Scraping: https://gizmodo.com/latest/page/64 links:1260
Scraping: https://gizmodo.com/latest/page/65 links:1280
Scraping: https://gizmodo.com/latest/page/66 links:1300
Scraping: https://gizmodo.com/latest/page/67 links:1320
Scraping: https://gizmodo.com/latest/page/68 links:1340
Scraping: https://gizmodo.com/latest/page/69 links:1360
Scraping: https://gizmodo.com/latest/page/70 links:1380
Scraping: https://gizmodo.com/latest/page/71 links:1400
Scraping: https://gizmodo.com/latest/page/72 links:1420
Scraping: https://gizmodo.com/latest/page/73 links:1440
Scraping: https://gizmodo.com/latest/page/74 links:1460
Scraping: https://gizmodo.com/latest/page/75 links:1480
Scraping: https://gizmodo.com/latest/page/76 links:1500
Scraping: https://gizmodo.com/latest/page/77 links:1520
Scraping: https://gizmodo.com/latest/page/78 links:1540
Scraping: https://gizmodo.com/latest/page/79 links:1560
Scraping: https://gizmodo.com/latest/page/80 links:1580
Scraping: https://gizmodo.com/latest/page/81 links:1600
Scraping: https://gizmodo.com/latest/page/82 links:1620
Scraping: https://gizmodo.com/latest/page/83 links:1640
Scraping: https://gizmodo.com/latest/page/84 links:1660
Scraping: https://gizmodo.com/latest/page/85 links:1680
Scraping: https://gizmodo.com/latest/page/86 links:1700
Scraping: https://gizmodo.com/latest/page/87 links:1720
Scraping: https://gizmodo.com/latest/page/88 links:1740
Scraping: https://gizmodo.com/latest/page/89 links:1760
Scraping: https://gizmodo.com/latest/page/90 links:1780
Scraping: https://gizmodo.com/latest/page/91 links:1800
Scraping: https://gizmodo.com/latest/page/92 links:1820
Scraping: https://gizmodo.com/latest/page/93 links:1840
Scraping: https://gizmodo.com/latest/page/94 links:1860
Scraping: https://gizmodo.com/latest/page/95 links:1880
Scraping: https://gizmodo.com/latest/page/96 links:1900
Scraping: https://gizmodo.com/latest/page/97 links:1920
Scraping: https://gizmodo.com/latest/page/98 links:1940
Scraping: https://gizmodo.com/latest/page/99 links:1960
Scraping: https://gizmodo.com/latest/page/100 links:1980
Scraping: https://gizmodo.com/latest/page/101 links:2000
Scraping: https://gizmodo.com/latest/page/102 links:2020
Scraping: https://gizmodo.com/latest/page/103 links:2040
Scraping: https://gizmodo.com/latest/page/104 links:2060
Scraping: https://gizmodo.com/latest/page/105 links:2080
Scraping: https://gizmodo.com/latest/page/106 links:2100
Scraping: https://gizmodo.com/latest/page/107 links:2120
Scraping: https://gizmodo.com/latest/page/108 links:2140
Scraping: https://gizmodo.com/latest/page/109 links:2160
Scraping: https://gizmodo.com/latest/page/110 links:2180
Scraping: https://gizmodo.com/latest/page/111 links:2200
Scraping: https://gizmodo.com/latest/page/112 links:2220
Scraping: https://gizmodo.com/latest/page/113 links:2240
Scraping: https://gizmodo.com/latest/page/114 links:2260
Scraping: https://gizmodo.com/latest/page/115 links:2280
Scraping: https://gizmodo.com/latest/page/116 links:2300
Scraping: https://gizmodo.com/latest/page/117 links:2320
Scraping: https://gizmodo.com/latest/page/118 links:2340
Scraping: https://gizmodo.com/latest/page/119 links:2360
Scraping: https://gizmodo.com/latest/page/120 links:2380
Scraping: https://gizmodo.com/latest/page/121 links:2400
Scraping: https://gizmodo.com/latest/page/122 links:2420
Scraping: https://gizmodo.com/latest/page/123 links:2440
Scraping: https://gizmodo.com/latest/page/124 links:2460
Scraping: https://gizmodo.com/latest/page/125 links:2480
Scraping: https://gizmodo.com/latest/page/126 links:2500
Scraping: https://gizmodo.com/latest/page/127 links:2520
Scraping: https://gizmodo.com/latest/page/128 links:2540
Scraping: https://gizmodo.com/latest/page/129 links:2560
Scraping: https://gizmodo.com/latest/page/130 links:2580
Scraping: https://gizmodo.com/latest/page/131 links:2600
Scraping: https://gizmodo.com/latest/page/132 links:2620
Scraping: https://gizmodo.com/latest/page/133 links:2640
Scraping: https://gizmodo.com/latest/page/134 links:2660
Scraping: https://gizmodo.com/latest/page/135 links:2680
Scraping: https://gizmodo.com/latest/page/136 links:2700
Scraping: https://gizmodo.com/latest/page/137 links:2720
Scraping: https://gizmodo.com/latest/page/138 links:2740
Scraping: https://gizmodo.com/latest/page/139 links:2760
Scraping: https://gizmodo.com/latest/page/140 links:2780
Scraping: https://gizmodo.com/latest/page/141 links:2800
Scraping: https://gizmodo.com/latest/page/142 links:2820
Scraping: https://gizmodo.com/latest/page/143 links:2840
Scraping: https://gizmodo.com/latest/page/144 links:2860
Scraping: https://gizmodo.com/latest/page/145 links:2880
Scraping: https://gizmodo.com/latest/page/146 links:2900
Scraping: https://gizmodo.com/latest/page/147 links:2920
Scraping: https://gizmodo.com/latest/page/148 links:2940
Scraping: https://gizmodo.com/latest/page/149 links:2960
Scraping: https://gizmodo.com/latest/page/150 links:2980
Scraping: https://gizmodo.com/latest/page/151 links:3000
Scraping: https://gizmodo.com/latest/page/152 links:3020
Scraping: https://gizmodo.com/latest/page/153 links:3040
Scraping: https://gizmodo.com/latest/page/154 links:3060
Scraping: https://gizmodo.com/latest/page/155 links:3080
Scraping: https://gizmodo.com/latest/page/156 links:3100
Scraping: https://gizmodo.com/latest/page/157 links:3120
Scraping: https://gizmodo.com/latest/page/158 links:3140
Scraping: https://gizmodo.com/latest/page/159 links:3160
Scraping: https://gizmodo.com/latest/page/160 links:3180
Scraping: https://gizmodo.com/latest/page/161 links:3200
Scraping: https://gizmodo.com/latest/page/162 links:3220
Scraping: https://gizmodo.com/latest/page/163 links:3240
Scraping: https://gizmodo.com/latest/page/164 links:3260
Cloudflare challenge detected. Waiting...
Scraping: https://gizmodo.com/latest/page/165 links:3280
Scraping: https://gizmodo.com/latest/page/166 links:3300
Scraping: https://gizmodo.com/latest/page/167 links:3320
Scraping: https://gizmodo.com/latest/page/168 links:3340
Scraping: https://gizmodo.com/latest/page/169 links:3360
Scraping: https://gizmodo.com/latest/page/170 links:3380
Scraping: https://gizmodo.com/latest/page/171 links:3400
Scraping: https://gizmodo.com/latest/page/172 links:3420
Scraping: https://gizmodo.com/latest/page/173 links:3440
Scraping: https://gizmodo.com/latest/page/174 links:3460
Scraping: https://gizmodo.com/latest/page/175 links:3480
Scraping: https://gizmodo.com/latest/page/176 links:3500
Scraping: https://gizmodo.com/latest/page/177 links:3520
Scraping: https://gizmodo.com/latest/page/178 links:3540
Scraping: https://gizmodo.com/latest/page/179 links:3560
Scraping: https://gizmodo.com/latest/page/180 links:3580
Scraping: https://gizmodo.com/latest/page/181 links:3600
Scraping: https://gizmodo.com/latest/page/182 links:3620
Scraping: https://gizmodo.com/latest/page/183 links:3640
Scraping: https://gizmodo.com/latest/page/184 links:3660
Scraping: https://gizmodo.com/latest/page/185 links:3680
Scraping: https://gizmodo.com/latest/page/186 links:3700
Scraping: https://gizmodo.com/latest/page/187 links:3720
Scraping: https://gizmodo.com/latest/page/188 links:3740
Scraping: https://gizmodo.com/latest/page/189 links:3760
Scraping: https://gizmodo.com/latest/page/190 links:3780
Scraping: https://gizmodo.com/latest/page/191 links:3800
Scraping: https://gizmodo.com/latest/page/192 links:3820
Scraping: https://gizmodo.com/latest/page/193 links:3840
Scraping: https://gizmodo.com/latest/page/194 links:3860
Scraping: https://gizmodo.com/latest/page/195 links:3880
Scraping: https://gizmodo.com/latest/page/196 links:3900
Scraping: https://gizmodo.com/latest/page/197 links:3920
Scraping: https://gizmodo.com/latest/page/198 links:3940
Scraping: https://gizmodo.com/latest/page/199 links:3960
Scraping: https://gizmodo.com/latest/page/200 links:3980
Scraping: https://gizmodo.com/latest/page/201 links:4000
Scraping: https://gizmodo.com/latest/page/202 links:4020
Scraping: https://gizmodo.com/latest/page/203 links:4040
Scraping: https://gizmodo.com/latest/page/204 links:4060
Scraping: https://gizmodo.com/latest/page/205 links:4080
Scraping: https://gizmodo.com/latest/page/206 links:4100
Scraping: https://gizmodo.com/latest/page/207 links:4120
Scraping: https://gizmodo.com/latest/page/208 links:4140
Scraping: https://gizmodo.com/latest/page/209 links:4160
Scraping: https://gizmodo.com/latest/page/210 links:4180
Scraping: https://gizmodo.com/latest/page/211 links:4200
Scraping: https://gizmodo.com/latest/page/212 links:4220
Scraping: https://gizmodo.com/latest/page/213 links:4240
Scraping: https://gizmodo.com/latest/page/214 links:4260
Scraping: https://gizmodo.com/latest/page/215 links:4280
Scraping: https://gizmodo.com/latest/page/216 links:4300
Scraping: https://gizmodo.com/latest/page/217 links:4320
Scraping: https://gizmodo.com/latest/page/218 links:4340
Scraping: https://gizmodo.com/latest/page/219 links:4360
Scraping: https://gizmodo.com/latest/page/220 links:4380
Scraping: https://gizmodo.com/latest/page/221 links:4400
Scraping: https://gizmodo.com/latest/page/222 links:4420
Scraping: https://gizmodo.com/latest/page/223 links:4440
Scraping: https://gizmodo.com/latest/page/224 links:4460
Scraping: https://gizmodo.com/latest/page/225 links:4480
Scraping: https://gizmodo.com/latest/page/226 links:4500
Scraping: https://gizmodo.com/latest/page/227 links:4520
Scraping: https://gizmodo.com/latest/page/228 links:4540
Scraping: https://gizmodo.com/latest/page/229 links:4560
Scraping: https://gizmodo.com/latest/page/230 links:4580
Scraping: https://gizmodo.com/latest/page/231 links:4600
Scraping: https://gizmodo.com/latest/page/232 links:4620
Scraping: https://gizmodo.com/latest/page/233 links:4640
Scraping: https://gizmodo.com/latest/page/234 links:4660
Scraping: https://gizmodo.com/latest/page/235 links:4680
Scraping: https://gizmodo.com/latest/page/236 links:4700
Scraping: https://gizmodo.com/latest/page/237 links:4720
Scraping: https://gizmodo.com/latest/page/238 links:4740
Scraping: https://gizmodo.com/latest/page/239 links:4760
Scraping: https://gizmodo.com/latest/page/240 links:4780
Scraping: https://gizmodo.com/latest/page/241 links:4800
Scraping: https://gizmodo.com/latest/page/242 links:4820
Scraping: https://gizmodo.com/latest/page/243 links:4840
Scraping: https://gizmodo.com/latest/page/244 links:4860
Scraping: https://gizmodo.com/latest/page/245 links:4880
Scraping: https://gizmodo.com/latest/page/246 links:4900
Scraping: https://gizmodo.com/latest/page/247 links:4920
Scraping: https://gizmodo.com/latest/page/248 links:4940
Scraping: https://gizmodo.com/latest/page/249 links:4960
Scraping: https://gizmodo.com/latest/page/250 links:4980
Scraping: https://gizmodo.com/latest/page/251 links:5000
Scraping: https://gizmodo.com/latest/page/252 links:5020
Scraping: https://gizmodo.com/latest/page/253 links:5040
Scraping: https://gizmodo.com/latest/page/254 links:5060
Scraping: https://gizmodo.com/latest/page/255 links:5080
Scraping: https://gizmodo.com/latest/page/256 links:5100
Scraping: https://gizmodo.com/latest/page/257 links:5120
Scraping: https://gizmodo.com/latest/page/258 links:5140
Scraping: https://gizmodo.com/latest/page/259 links:5160
Scraping: https://gizmodo.com/latest/page/260 links:5180
Scraping: https://gizmodo.com/latest/page/261 links:5200
Scraping: https://gizmodo.com/latest/page/262 links:5220
Scraping: https://gizmodo.com/latest/page/263 links:5240
Scraping: https://gizmodo.com/latest/page/264 links:5260
Scraping: https://gizmodo.com/latest/page/265 links:5280
Scraping: https://gizmodo.com/latest/page/266 links:5300
Scraping: https://gizmodo.com/latest/page/267 links:5320
Scraping: https://gizmodo.com/latest/page/268 links:5340
Scraping: https://gizmodo.com/latest/page/269 links:5360
Scraping: https://gizmodo.com/latest/page/270 links:5380
Scraping: https://gizmodo.com/latest/page/271 links:5400
Scraping: https://gizmodo.com/latest/page/272 links:5420
Scraping: https://gizmodo.com/latest/page/273 links:5440
Scraping: https://gizmodo.com/latest/page/274 links:5460
Scraping: https://gizmodo.com/latest/page/275 links:5480
Scraping: https://gizmodo.com/latest/page/276 links:5500
Scraping: https://gizmodo.com/latest/page/277 links:5520
Scraping: https://gizmodo.com/latest/page/278 links:5540
Scraping: https://gizmodo.com/latest/page/279 links:5560
Scraping: https://gizmodo.com/latest/page/280 links:5580
Scraping: https://gizmodo.com/latest/page/281 links:5600
Scraping: https://gizmodo.com/latest/page/282 links:5620
Scraping: https://gizmodo.com/latest/page/283 links:5640
Scraping: https://gizmodo.com/latest/page/284 links:5660
Scraping: https://gizmodo.com/latest/page/285 links:5680
Scraping: https://gizmodo.com/latest/page/286 links:5700
Scraping: https://gizmodo.com/latest/page/287 links:5720
Scraping: https://gizmodo.com/latest/page/288 links:5740
Scraping: https://gizmodo.com/latest/page/289 links:5760
Scraping: https://gizmodo.com/latest/page/290 links:5780
Scraping: https://gizmodo.com/latest/page/291 links:5800
Scraping: https://gizmodo.com/latest/page/292 links:5820
Scraping: https://gizmodo.com/latest/page/293 links:5840
Scraping: https://gizmodo.com/latest/page/294 links:5860
Scraping: https://gizmodo.com/latest/page/295 links:5880
Scraping: https://gizmodo.com/latest/page/296 links:5900
Scraping: https://gizmodo.com/latest/page/297 links:5920
Scraping: https://gizmodo.com/latest/page/298 links:5940
Scraping: https://gizmodo.com/latest/page/299 links:5960
Scraping: https://gizmodo.com/latest/page/300 links:5980
Scraping: https://gizmodo.com/latest/page/301 links:6000
Scraping: https://gizmodo.com/latest/page/302 links:6020
Scraping: https://gizmodo.com/latest/page/303 links:6040
Scraping: https://gizmodo.com/latest/page/304 links:6060
Scraping: https://gizmodo.com/latest/page/305 links:6080
Scraping: https://gizmodo.com/latest/page/306 links:6100
Scraping: https://gizmodo.com/latest/page/307 links:6120
Scraping: https://gizmodo.com/latest/page/308 links:6140
Scraping: https://gizmodo.com/latest/page/309 links:6160
Scraping: https://gizmodo.com/latest/page/310 links:6180
Scraping: https://gizmodo.com/latest/page/311 links:6200
Scraping: https://gizmodo.com/latest/page/312 links:6220
Scraping: https://gizmodo.com/latest/page/313 links:6240
Scraping: https://gizmodo.com/latest/page/314 links:6260
Scraping: https://gizmodo.com/latest/page/315 links:6280
Scraping: https://gizmodo.com/latest/page/316 links:6300
Scraping: https://gizmodo.com/latest/page/317 links:6320
Scraping: https://gizmodo.com/latest/page/318 links:6340
Scraping: https://gizmodo.com/latest/page/319 links:6360
Scraping: https://gizmodo.com/latest/page/320 links:6380
Scraping: https://gizmodo.com/latest/page/321 links:6400
Scraping: https://gizmodo.com/latest/page/322 links:6420
Scraping: https://gizmodo.com/latest/page/323 links:6440
Scraping: https://gizmodo.com/latest/page/324 links:6460
Scraping: https://gizmodo.com/latest/page/325 links:6480
Scraping: https://gizmodo.com/latest/page/326 links:6500
Scraping: https://gizmodo.com/latest/page/327 links:6520
Scraping: https://gizmodo.com/latest/page/328 links:6540
Scraping: https://gizmodo.com/latest/page/329 links:6560
Scraping: https://gizmodo.com/latest/page/330 links:6580
Scraping: https://gizmodo.com/latest/page/331 links:6600
Scraping: https://gizmodo.com/latest/page/332 links:6620
Scraping: https://gizmodo.com/latest/page/333 links:6640
Scraping: https://gizmodo.com/latest/page/334 links:6660
Scraping: https://gizmodo.com/latest/page/335 links:6680
Scraping: https://gizmodo.com/latest/page/336 links:6700
Scraping: https://gizmodo.com/latest/page/337 links:6720
Scraping: https://gizmodo.com/latest/page/338 links:6740
Scraping: https://gizmodo.com/latest/page/339 links:6760
Scraping: https://gizmodo.com/latest/page/340 links:6780
Scraping: https://gizmodo.com/latest/page/341 links:6800
Scraping: https://gizmodo.com/latest/page/342 links:6820
Scraping: https://gizmodo.com/latest/page/343 links:6840
Scraping: https://gizmodo.com/latest/page/344 links:6860
Scraping: https://gizmodo.com/latest/page/345 links:6880
Scraping: https://gizmodo.com/latest/page/346 links:6900
Scraping: https://gizmodo.com/latest/page/347 links:6920
Scraping: https://gizmodo.com/latest/page/348 links:6940
Scraping: https://gizmodo.com/latest/page/349 links:6960
Scraping: https://gizmodo.com/latest/page/350 links:6980
Scraping: https://gizmodo.com/latest/page/351 links:7000
Scraping: https://gizmodo.com/latest/page/352 links:7020
Scraping: https://gizmodo.com/latest/page/353 links:7040

In [59]:
len(titles)

12

In [20]:
df = pd.DataFrame(data={'titles':titles,'links':links,'dates':dates})

In [21]:
df.to_csv('ahrefs_1.csv',index=False)

In [73]:
len(links)

20

In [61]:
len(dates)

12

In [62]:
dates

[None, None, None, None, None, None, None, None, None, None, None, None]

In [63]:
titles

['‘Alexa, Pay for Gas’ Is Amazon’s Latest IoT Honey Trap',
 '‘Alexa, Pay for Gas’ Is Amazon’s Latest IoT Honey Trap',
 'This Beautiful Smartphone Is Like an Affordable Samsung Galaxy S10',
 'The First Folding PC Is Remarkably Smart',
 'A Bed That Cools and Heats Each Sleeper Separately Will Save Countless Relationships',
 'A Smart Wooden Stick Is Now a Thing That Exists',
 'Samsung Might Have Just Made the Nicest Chromebook Ever',
 'Why Did the Pentagon Push the FDA to Approve a Powerful New Opioid?',
 'Disney+ Edits Out Goofy’s Smoking Scene in Supposedly Uncut Version of Classic Movie',
 'During Brain Surgery, This AI Can Diagnose a Tumor in 2 Minutes',
 'This Company Just Gave Dudes a Good Reason to Shave Their Taints',
 'What Was the Most Fun Thing Humans Could Do 5,000 Years Ago?']

In [13]:
len(links)

54961

In [14]:
df = pd.DataFrame(data={"links":links},columns=["links"])

In [15]:
df.head()

                                               links
0  https://gizmodo.com/10-things-to-remember-abou...
1  https://gizmodo.com/bitcoin-price-plunges-six-...
2  https://gizmodo.com/this-stunning-predator-bad...
3  https://gizmodo.com/doctor-who-war-between-lan...
4  https://gizmodo.com/california-startup-flies-m...

In [16]:
df.to_csv('gizmodo_links.csv',index=False)

In [18]:
df['links'].iloc[0]

'https://gizmodo.com/10-things-to-remember-about-five-nights-at-freddys-2000685629'

In [1]:
import json
import multiprocessing
import random
from datetime import datetime

In [3]:
df = pd.read_csv('gizmodo_links.csv')

In [4]:
links=df['links']
len(links)
links = df['links'].tolist()

In [6]:
idxs = [f"{s[0]}-{s[-1]}" for s in np.array_split(np.arange(len(links)), 24)]

In [65]:
quarters = [(1,3),(4,6),(7,9),(10,12)]

In [32]:
from selenium_stealth import stealth
from selenium.webdriver.remote.remote_connection import RemoteConnection
def new_driver():
    options = uc.ChromeOptions()
    driver = uc.Chrome(
        use_subprocess=True,
        options=options,
        client_config={
            "connection_timeout": 300,  
            "read_timeout": 300          
        }
    )
    return driver
driver=new_driver()

In [5]:
df_final = pd.DataFrame(columns=["titles", "contents", "links","dates"])
df_any = pd.DataFrame(columns=["titles", "contents", "links","dates","year","month","quarter"])

In [23]:
df_final = pd.read_csv('gizmodo_contents.csv')

In [66]:
def init_year_hashmap(year):
    return {q: pd.DataFrame(columns=["titles", "contents", "links", "dates", "year", "month", "quarter"]) for q in range(1, 5)}

df_any_map = {} 

for y in range(2020,2025):
    df_any_map[y] = init_year_hashmap(y)

In [76]:
def scrape_links(links):
    global driver, df_final, df_any_map
    saved_quarters = set([(2024, 3),(2024, 2)])
    chosen_links = []
    display_handle = display("", display_id=True)
    def year_full(year):
        return all(len(df_any_map.get(year, {}).get(q, pd.DataFrame())) >= 500 for q in range(1, 5))

    i = 0
    while i < len(links):
        url = links[i]

        if year_full(2020):
            print("Year 2020 fully scraped. Stopping.")
            break
    
        try:
            if url in chosen_links:
                i += 1
                continue
            chosen_links.append(url)
    
            driver.get(url)
            time.sleep(random.uniform(3.5, 7.0))
            html = driver.page_source
    
            if "Just a moment" in html:
                driver.quit()
                driver = new_driver()
                driver.get(url)
                time.sleep(random.uniform(3.5, 7.0))
                html = driver.page_source
                if "Just a moment" in html:
                    driver.quit()
                    driver = new_driver()
                    print("Blocked, skipping page")
                    i += 1
                    continue
    
            soup = BeautifulSoup(html, "html.parser")
            datetag = soup.select_one(
                'time.updated.typo-space-h5.md\\:typo-space-h3.uppercase.text-grey-600.dark\\:text-grey-200'
            )
            if not datetag:
                i += 1
                continue
            date = datetime.fromisoformat(datetag['datetime'])
            month = date.month
            year = date.year
            quarter = (month - 1)//3 + 1
    
            # Build entry
            title = soup.select_one('h1.typo-sofia-h4.md\\:typo-sofia-h3')
            subtitle = soup.select_one('div.post-excerpt.mt-5.typo-space-body-2.md\\:typo-space-body-1')
            content = soup.select_one('article.post')
            content_text = ""
            if subtitle: content_text += subtitle.get_text(" ", strip=True) + " "
            if content: content_text += content.get_text(" ", strip=True)
    
            entry = {
                "titles": title.get_text(" ", strip=True) if title else "",
                "contents": content_text,
                "links": url,
                "dates": date,
                "year": year,
                "month": month,
                "quarter": quarter
            }
    
            if year not in df_any_map:
                df_any_map[year] = {q: pd.DataFrame(columns=df_final.columns) for q in range(1,5)}
            local_count_year = sum(len(df_any_map[year][q]) for q in range(1,5))
            display_handle.update(
                f"Scraped: {url} | Year: {year} Q{quarter} | Local Year:{local_count_year}  Q: {len(df_any_map[year][quarter])}"
            )
            if url in df_any_map[year][quarter]['links'].values:
                i+=1
                continue
            if (year, quarter) not in saved_quarters:
                df_any_map[year][quarter] = pd.concat(
                    [df_any_map[year][quarter], pd.DataFrame([entry])], ignore_index=True
                )
                if len(df_any_map[year][quarter]) >= 500:
                    df_final = pd.concat([df_final, df_any_map[year][quarter]], ignore_index=True)
                    df_final.to_csv('gizmodo_contents.csv', index=False)
                    print(f"Quarter reached 500 entries: Year {year} Q{quarter}, saved to CSV")
                    saved_quarters.add((year, quarter))
                    i += 100
                else:
                    i += 1
                    
            else:
                i += 100
                continue
    
        except Exception as e:
            print("Error:", e)
            if "Read timed out" in str(e):
                driver.quit()
                driver = new_driver()
            time.sleep(5)
            i += 1

In [77]:
scrape_links(links[13000:])

'Scraped: https://gizmodo.com/trump-approves-bill-barring-rural-telecom-carriers-from-1842302739 | Year: 2020 Q1 | Local Year:1999  Q: 499'

Error: HTTPConnectionPool(host='localhost', port=59179): Read timed out. (read timeout=120)
Quarter reached 500 entries: Year 2024 Q1, saved to CSV
Blocked, skipping page
Blocked, skipping page
Blocked, skipping page
Blocked, skipping page
Quarter reached 500 entries: Year 2023 Q4, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2023 Q3, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2023 Q2, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2023 Q1, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2022 Q4, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2022 Q3, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2022 Q2, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Blocked, skipping page
Quarter reached 500 entries: Year 2022 Q1, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2021 Q4, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2021 Q3, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2021 Q2, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2021 Q1, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2020 Q4, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2020 Q3, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Error: HTTPConnectionPool(host='localhost', port=51877): Read timed out. (read timeout=120)
Quarter reached 500 entries: Year 2020 Q2, saved to CSV

E:\Temp\ipykernel_28312\4226795174.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_any_map[year][quarter] = pd.concat(

Quarter reached 500 entries: Year 2020 Q1, saved to CSV
Year 2020 fully scraped. Stopping.

In [81]:
for i in [2024,2023,2022,2021,2020]:
    for j in [1,2,3,4]:
        print(df_any_map[i][j].shape)

(501, 7)
(501, 7)
(0, 7)
(0, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)
(500, 7)

In [26]:
df_final.iloc[:-1000]

,titles,contents,links,dates,year,month,quarter
0,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...","This Thanksgiving season, feed your 'Frankenst...",https://gizmodo.com/you-can-read-guillermo-del...,2025-10-25 16:15:23-04:00,NaN,NaN,NaN
1,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...","'Five Nights at Freddy's 2', starring Josh Hut...",https://gizmodo.com/five-nights-at-freddys-2-t...,2025-11-05 09:00:48-05:00,NaN,NaN,NaN
2,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...",The company says it’s adding new “guardrails” ...,https://gizmodo.com/openai-blocks-users-from-m...,2025-10-17 10:40:25-04:00,NaN,NaN,NaN
3,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...",Adam Raine's family members added troubling ne...,https://gizmodo.com/openai-weakened-chatgpts-s...,2025-10-23 07:05:31-04:00,NaN,NaN,NaN
4,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...",It's against Facebook's terms of service to re...,https://gizmodo.com/facebook-removes-ice-track...,2025-10-14 16:15:01-04:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2495,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...",The iPhone 16 didn't disappoint and IFA 2024 g...,https://gizmodo.com/the-best-gadgets-of-septem...,2024-10-01 09:45:43-04:00,NaN,NaN,NaN
2496,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...","It's coming to the Sony WH-1000XM5, WF-1000XM5...",https://gizmodo.com/sonys-headphones-are-getti...,2024-10-04 17:15:35-04:00,NaN,NaN,NaN
2497,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...",NASA selected two space observatory proposals ...,https://gizmodo.com/one-of-these-two-space-obs...,2024-10-08 13:45:27-04:00,NaN,NaN,NaN
2498,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...",The yet-to-be-named comet will make its closes...,https://gizmodo.com/new-sungrazing-comet-may-o...,2024-10-01 15:15:46-04:00,NaN,NaN,NaN
2499,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...",The teeny tiny iPad Mini may still be barely b...,https://gizmodo.com/ipad-mini-is-back-and-appl...,2024-10-15 10:21:18-04:00,NaN,NaN,NaN

In [131]:
df_any['year']=df_any['dates'].map(lambda x:x.year)
df_any['month']=df_any['dates'].map(lambda x:x.month)

In [133]:
df_any['quarter'] = ((df_any['month'] - 1) // 3 + 1)

In [141]:
df_any.head()

Empty DataFrame
Columns: [titles, contents, links, dates]
Index: []

In [139]:
df_any.to_csv('gizmodo_any.csv', index=False)

In [168]:
df_any

,titles,contents,links,dates,year,month,quarter
0,"[\n Cops Pose Before a $200,000 Mount...",A three-month investigation into retail theft ...,https://gizmodo.com/cops-pose-before-a-200000-...,2024-07-10 09:50:23-04:00,NaN,NaN,NaN
1,"[\n No, That Acolyte Planet Is Not Wh...",Leslye Headland has seen your speculation abou...,https://gizmodo.com/star-wars-the-acolyte-unkn...,2024-07-05 18:30:10-04:00,NaN,NaN,NaN
2,"[\n, [Fallout’s], Vinyl Soundtrack Is Coming,...",Ella Purnell and Walton Goggins star in the Pr...,https://gizmodo.com/fallout-tv-show-vinyl-musi...,2024-04-24 13:00:01-04:00,NaN,NaN,NaN
3,[\n Mark Hamill Talks About His Hairy...,The Star Wars legend was part of a San Diego C...,https://gizmodo.com/sdcc-2024-mark-hamill-drea...,2024-07-28 17:15:35-04:00,NaN,NaN,NaN
4,[\n The Best Gadgets of June 2024\n ...,There's no time for summertime sadness with ga...,https://gizmodo.com/best-gadgets-of-june-2024-...,2024-07-01 22:05:01-04:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1972,[\n Chromecast With Google TV Might F...,A new dongle for the 4K streaming crowd could ...,https://gizmodo.com/google-tv-chromecast-4k-18...,2024-04-23 15:10:01-04:00,NaN,NaN,NaN
1973,[\n Amazon Is Ready For Even More of ...,"Plus, Doctor Who 's Russell T Davies teases w...",https://gizmodo.com/the-boys-season-5-amazon-p...,2024-05-14 10:30:00-04:00,NaN,NaN,NaN
1974,"[\n Lego’s New , [Jaws], Set Will No...","The 1,497-piece tribute to the Steven Spielber...",https://gizmodo.com/lego-ideas-jaws-set-price-...,2024-07-04 09:00:33-04:00,NaN,NaN,NaN
1975,"[\n First Trailer for , [Rick and Mor...",Adult Swim's riff on the blockbuster animated ...,https://gizmodo.com/first-trailer-for-rick-and...,2024-07-11 14:45:32-04:00,NaN,NaN,NaN
1976,"[\n Russell T Davies’ Dream , [Star T...","""Borg, Borg, Borg! I love the Borg!"", Davies b...",https://gizmodo.com/sdcc-2024-doctor-who-star-...,2024-07-28 16:30:03-04:00,NaN,NaN,NaN

In [82]:
df_test = pd.read_csv('gizmodo_contents.csv')

In [83]:
df_test

,titles,contents,links,dates,year,month,quarter
0,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...","This Thanksgiving season, feed your 'Frankenst...",https://gizmodo.com/you-can-read-guillermo-del...,2025-10-25 16:15:23-04:00,NaN,NaN,NaN
1,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...","'Five Nights at Freddy's 2', starring Josh Hut...",https://gizmodo.com/five-nights-at-freddys-2-t...,2025-11-05 09:00:48-05:00,NaN,NaN,NaN
2,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...",The company says it’s adding new “guardrails” ...,https://gizmodo.com/openai-blocks-users-from-m...,2025-10-17 10:40:25-04:00,NaN,NaN,NaN
3,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...",Adam Raine's family members added troubling ne...,https://gizmodo.com/openai-weakened-chatgpts-s...,2025-10-23 07:05:31-04:00,NaN,NaN,NaN
4,"<h1 class=""typo-sofia-h4 md:typo-sofia-h3"">\n ...",It's against Facebook's terms of service to re...,https://gizmodo.com/facebook-removes-ice-track...,2025-10-14 16:15:01-04:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...
13998,Bill Barr Recently Met With Australian Officia...,"Peter Dutton, Australia’s Home Affairs Ministe...",https://gizmodo.com/bill-barr-recently-met-wit...,2020-03-13 05:30:00-04:00,2020.0,3.0,1.0
13999,An Explosive Clone Wars Episode Asks the Price...,There’s a moment in this week’s Star Wars: The...,https://gizmodo.com/an-explosive-clone-wars-ep...,2020-03-13 03:01:00-04:00,2020.0,3.0,1.0
14000,Sennheiser’s New Wireless Earbuds Up the Ante ...,Sennheiser’s Momentum True Wireless earbuds de...,https://gizmodo.com/sennheisers-new-wireless-e...,2020-03-13 03:00:01-04:00,2020.0,3.0,1.0
14001,"Google, Facebook Contractors Still Expected On...",The tumultuous divide between full-time staff ...,https://gizmodo.com/google-facebook-contractor...,2020-03-13 02:36:00-04:00,2020.0,3.0,1.0
14002,Trump Approves Bill Barring Rural Telecom Carr...,President Donald Trump signed the so-called “r...,https://gizmodo.com/trump-approves-bill-barrin...,2020-03-12 21:02:01-04:00,2020.0,3.0,1.0