In [27]:
import urllib.request
import requests
import bs4
from bs4 import BeautifulSoup
import time
import random
import undetected_chromedriver as uc
import pandas as pd
import os
import subprocess
import numpy as np

In [3]:
BASE_URL = "https://machinelearningmastery.com/blog/page/{}"

In [2]:
driver = uc.Chrome()

driver.get("https://lifehacker.com/latest/page/3")
html = driver.page_source

In [ ]:
html

In [3]:
soup = BeautifulSoup(html, "html.parser")

found_titles = soup.select("a[data-ga-item='title']")

In [28]:
found_titles

[<a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="Google Maps' New Power Saving Mode Only Works on One Type of Phone, and That Stinks" data-ga-position="0" href="/tech/google-map-power-saving-mode-pixel-10">
                                 Google Maps' New Power Saving Mode Only Works on One Type of Phone, and That Stinks
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="These Bose QuietComfort Ultra Earbuds Are $50 Off Right Now" data-ga-position="1" href="/tech/bose-quietcomfort-ultra-earbuds-2nd-gen-deal">
                                 These Bose QuietComfort Ultra Earbuds Are $50 Off Right Now
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="This Amazon Fire Max 11 Tablet Is $75 Off Right Now" data-ga-position="2" href="/tech/amazons-fire-max-11-refurbished-sale">
                                 This Amazon Fire Max 11 Tablet Is $75 Off Right Now
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="ViWoods AiPaper Reader Review: Another Phone-Shaped E-Reader Has Entered the Chat" data-ga-position="3" href="/tech/viwoods-aipaper-reader-review">
                                 ViWoods AiPaper Reader Review: Another Phone-Shaped E-Reader Has Entered the Chat
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="Five Ways to Share Your Mouse and Keyboard Between Multiple Computers" data-ga-position="4" href="/tech/share-mouse-and-keyboard-with-multiple-computers">
                                 Five Ways to Share Your Mouse and Keyboard Between Multiple Computers
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="Use the '3-3-3' Method to Space Out Your Tasks and Get More Done" data-ga-position="5" href="/structure-your-day-with-the-3-3-3-method">
                                 Use the '3-3-3' Method to Space Out Your Tasks and Get More Done
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="Which Is Better: Coros Pace 3 vs. Coros Pace 4" data-ga-position="6" href="/health/coros-pace-3-vs-coros-pace-4">
                                 Which Is Better: Coros Pace 3 vs. Coros Pace 4
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="Microsoft (Sort of) Made a Ninite Alternative" data-ga-position="7" href="/tech/microsoft-sort-of-made-a-ninite-alternative">
                                 Microsoft (Sort of) Made a Ninite Alternative
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="This Lenovo ThinkCentre Mini PC Is on Sale for Under $500 Right Now" data-ga-position="8" href="/tech/lenovo-thinkcentre-mini-pc-stacksocial-sale-november-2025">
                                 This Lenovo ThinkCentre Mini PC Is on Sale for Under $500 Right Now
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="Use Time-Blocking to Proactively Schedule Out Your Day" data-ga-position="9" href="/use-time-blocking-to-proactively-schedule-out-your-day">
                                 Use Time-Blocking to Proactively Schedule Out Your Day
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="You Can Get This Lenovo IdeaPad 5 Touch on Sale for $600 Right Now" data-ga-position="10" href="/tech/lenovo-ideapad-5-touch-stacksocial-sale-november-2025">
                                 You Can Get This Lenovo IdeaPad 5 Touch on Sale for $600 Right Now
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="Whoop Has a New, Cheaper Subscription Using Its Old 4.0 Hardware" data-ga-position="11" href="/health/whoop-launches-its-50-and-mg-hardware-and-adds-pricing-tiers">
                                 Whoop Has a New, Cheaper Subscription Using Its Old 4.0 Hardware
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="What People Are Getting Wrong This Week: Kim Kardashian Debunks Psychics" data-ga-position="12" href="/entertainment/kim-kardashian-debunks-psychics">
                                 What People Are Getting Wrong This Week: Kim Kardashian Debunks Psychics
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="The Google Play Store Wants to Help Preserve Your Battery" data-ga-position="13" href="/tech/the-google-play-store-wants-to-help-preserve-your-battery">
                                 The Google Play Store Wants to Help Preserve Your Battery
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="Update Windows ASAP to Patch Another Zero-Day Vulnerability" data-ga-position="14" href="/tech/update-windows-asap-to-patch-this-zero-day-vulnerability">
                                 Update Windows ASAP to Patch Another Zero-Day Vulnerability
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="All My Favorite At-Home Workout Tools That Cost Less Than $25" data-ga-position="15" href="/health/my-favorite-at-home-workout-tools-under-25-dollars">
                                 All My Favorite At-Home Workout Tools That Cost Less Than $25
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="You Can Get This Lenovo Wired Desktop Speaker Set on Sale for Just $17 Right Now" data-ga-position="16" href="/tech/lenovo-desktop-speaker-stacksocial-sale-november-2025">
                                 You Can Get This Lenovo Wired Desktop Speaker Set on Sale for Just $17 Right Now
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="Four Tools You Can Use to Find Any Leak in Your Home" data-ga-position="17" href="/home/best-tools-to-find-any-leak-in-your-home">
                                 Four Tools You Can Use to Find Any Leak in Your Home
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="12 Shows Like 'The Lowdown' You Should Watch Next" data-ga-position="18" href="/entertainment/shows-like-the-lowdown">
                                 12 Shows Like 'The Lowdown' You Should Watch Next
                             </a>,
 <a class="hover:custom-underline mt-2 block font-akshar text-xl font-medium leading-tight tracking-wide" data-ga-click="" data-ga-item="title" data-ga-label="All the New AI Features Coming Soon to Google Photos" data-ga-position="19" href="/tech/google-photos-is-rolling-out-new-ai-features-today">
                                 All the New AI Features Coming Soon to Google Photos
                             </a>]

In [3]:
titles = []
links = []
dates = []
content = []

In [4]:
for i in range(1, 1307):
    url = f"https://lifehacker.com/latest/page/{i}"
    print(f"Scraping: {url} titles: {len(titles)} links: {len(links)} dates: {len(dates)}")

    try:
        driver.get(url)
        time.sleep(random.uniform(2.5, 4.0)) 
        html = driver.page_source

        if "Just a moment" in html:
            print("Cloudflare challenge")
            time.sleep(10)
            html = driver.page_source
            if "Just a moment" in html:
                print("Blocked, skip page")
                continue
        
        soup = BeautifulSoup(html, "html.parser")
        
        found_titles = soup.select("a[data-ga-item='title']")
        found_dates = soup.select("time")
        
        for el in found_titles:
            titles.append(el.get_text(strip=True))
            links.append(el.get("href"))

        for d in found_dates:
            dates.append(d.get_text(strip=True))

    except Exception as e:
        print("Error:", e)
        time.sleep(10)
        continue

Scraping: https://lifehacker.com/latest/page/1 titles: 0 links: 0 dates: 0
Scraping: https://lifehacker.com/latest/page/2 titles: 25 links: 25 dates: 25
Scraping: https://lifehacker.com/latest/page/3 titles: 45 links: 45 dates: 45
Scraping: https://lifehacker.com/latest/page/4 titles: 65 links: 65 dates: 65
Scraping: https://lifehacker.com/latest/page/5 titles: 85 links: 85 dates: 85
Scraping: https://lifehacker.com/latest/page/6 titles: 105 links: 105 dates: 105
Scraping: https://lifehacker.com/latest/page/7 titles: 125 links: 125 dates: 125
Scraping: https://lifehacker.com/latest/page/8 titles: 145 links: 145 dates: 145
Scraping: https://lifehacker.com/latest/page/9 titles: 165 links: 165 dates: 165
Scraping: https://lifehacker.com/latest/page/10 titles: 185 links: 185 dates: 185
Scraping: https://lifehacker.com/latest/page/11 titles: 205 links: 205 dates: 205
Scraping: https://lifehacker.com/latest/page/12 titles: 225 links: 225 dates: 225
Scraping: https://lifehacker.com/latest/page/13 titles: 245 links: 245 dates: 245
Scraping: https://lifehacker.com/latest/page/14 titles: 265 links: 265 dates: 265
Scraping: https://lifehacker.com/latest/page/15 titles: 285 links: 285 dates: 285
Scraping: https://lifehacker.com/latest/page/16 titles: 305 links: 305 dates: 305
Scraping: https://lifehacker.com/latest/page/17 titles: 325 links: 325 dates: 325
Scraping: https://lifehacker.com/latest/page/18 titles: 345 links: 345 dates: 345
Scraping: https://lifehacker.com/latest/page/19 titles: 365 links: 365 dates: 365
Scraping: https://lifehacker.com/latest/page/20 titles: 385 links: 385 dates: 385
Scraping: https://lifehacker.com/latest/page/21 titles: 405 links: 405 dates: 405
Scraping: https://lifehacker.com/latest/page/22 titles: 425 links: 425 dates: 425
Scraping: https://lifehacker.com/latest/page/23 titles: 445 links: 445 dates: 445
Scraping: https://lifehacker.com/latest/page/24 titles: 465 links: 465 dates: 465
Scraping: https://lifehacker.com/latest/page/25 titles: 485 links: 485 dates: 485
Scraping: https://lifehacker.com/latest/page/26 titles: 505 links: 505 dates: 505
Scraping: https://lifehacker.com/latest/page/27 titles: 525 links: 525 dates: 525
Scraping: https://lifehacker.com/latest/page/28 titles: 545 links: 545 dates: 545
Scraping: https://lifehacker.com/latest/page/29 titles: 565 links: 565 dates: 565
Scraping: https://lifehacker.com/latest/page/30 titles: 585 links: 585 dates: 585
Scraping: https://lifehacker.com/latest/page/31 titles: 605 links: 605 dates: 605
Scraping: https://lifehacker.com/latest/page/32 titles: 625 links: 625 dates: 625
Scraping: https://lifehacker.com/latest/page/33 titles: 645 links: 645 dates: 645
Scraping: https://lifehacker.com/latest/page/34 titles: 665 links: 665 dates: 665
Scraping: https://lifehacker.com/latest/page/35 titles: 685 links: 685 dates: 685
Scraping: https://lifehacker.com/latest/page/36 titles: 705 links: 705 dates: 705
Scraping: https://lifehacker.com/latest/page/37 titles: 725 links: 725 dates: 725
Scraping: https://lifehacker.com/latest/page/38 titles: 745 links: 745 dates: 745
Scraping: https://lifehacker.com/latest/page/39 titles: 765 links: 765 dates: 765
Scraping: https://lifehacker.com/latest/page/40 titles: 785 links: 785 dates: 785
Scraping: https://lifehacker.com/latest/page/41 titles: 805 links: 805 dates: 805
Scraping: https://lifehacker.com/latest/page/42 titles: 825 links: 825 dates: 825
Scraping: https://lifehacker.com/latest/page/43 titles: 845 links: 845 dates: 845
Scraping: https://lifehacker.com/latest/page/44 titles: 865 links: 865 dates: 865
Scraping: https://lifehacker.com/latest/page/45 titles: 885 links: 885 dates: 885
Scraping: https://lifehacker.com/latest/page/46 titles: 905 links: 905 dates: 905
Scraping: https://lifehacker.com/latest/page/47 titles: 925 links: 925 dates: 925
Scraping: https://lifehacker.com/latest/page/48 titles: 945 links: 945 dates: 945
Scraping: https://lifehacker.com/latest/page/49 titles: 965 links: 965 dates: 965
Scraping: https://lifehacker.com/latest/page/50 titles: 985 links: 985 dates: 985
Scraping: https://lifehacker.com/latest/page/51 titles: 1005 links: 1005 dates: 1005
Scraping: https://lifehacker.com/latest/page/52 titles: 1025 links: 1025 dates: 1025
Scraping: https://lifehacker.com/latest/page/53 titles: 1045 links: 1045 dates: 1045
Scraping: https://lifehacker.com/latest/page/54 titles: 1065 links: 1065 dates: 1065
Scraping: https://lifehacker.com/latest/page/55 titles: 1085 links: 1085 dates: 1085
Scraping: https://lifehacker.com/latest/page/56 titles: 1105 links: 1105 dates: 1105
Scraping: https://lifehacker.com/latest/page/57 titles: 1125 links: 1125 dates: 1125
Scraping: https://lifehacker.com/latest/page/58 titles: 1145 links: 1145 dates: 1145
Scraping: https://lifehacker.com/latest/page/59 titles: 1165 links: 1165 dates: 1165
Scraping: https://lifehacker.com/latest/page/60 titles: 1185 links: 1185 dates: 1185
Scraping: https://lifehacker.com/latest/page/61 titles: 1205 links: 1205 dates: 1205
Scraping: https://lifehacker.com/latest/page/62 titles: 1225 links: 1225 dates: 1225
Scraping: https://lifehacker.com/latest/page/63 titles: 1245 links: 1245 dates: 1245
Scraping: https://lifehacker.com/latest/page/64 titles: 1265 links: 1265 dates: 1265
Scraping: https://lifehacker.com/latest/page/65 titles: 1285 links: 1285 dates: 1285
Scraping: https://lifehacker.com/latest/page/66 titles: 1305 links: 1305 dates: 1305
Scraping: https://lifehacker.com/latest/page/67 titles: 1325 links: 1325 dates: 1325
Scraping: https://lifehacker.com/latest/page/68 titles: 1345 links: 1345 dates: 1345
Scraping: https://lifehacker.com/latest/page/69 titles: 1365 links: 1365 dates: 1365
Scraping: https://lifehacker.com/latest/page/70 titles: 1385 links: 1385 dates: 1385
Scraping: https://lifehacker.com/latest/page/71 titles: 1405 links: 1405 dates: 1405
Scraping: https://lifehacker.com/latest/page/72 titles: 1425 links: 1425 dates: 1425
Scraping: https://lifehacker.com/latest/page/73 titles: 1445 links: 1445 dates: 1445
Scraping: https://lifehacker.com/latest/page/74 titles: 1465 links: 1465 dates: 1465
Scraping: https://lifehacker.com/latest/page/75 titles: 1485 links: 1485 dates: 1485
Scraping: https://lifehacker.com/latest/page/76 titles: 1505 links: 1505 dates: 1505
Scraping: https://lifehacker.com/latest/page/77 titles: 1525 links: 1525 dates: 1525
Scraping: https://lifehacker.com/latest/page/78 titles: 1545 links: 1545 dates: 1545
Scraping: https://lifehacker.com/latest/page/79 titles: 1565 links: 1565 dates: 1565
Scraping: https://lifehacker.com/latest/page/80 titles: 1585 links: 1585 dates: 1585
Scraping: https://lifehacker.com/latest/page/81 titles: 1605 links: 1605 dates: 1605
Scraping: https://lifehacker.com/latest/page/82 titles: 1625 links: 1625 dates: 1625
Scraping: https://lifehacker.com/latest/page/83 titles: 1645 links: 1645 dates: 1645
Scraping: https://lifehacker.com/latest/page/84 titles: 1665 links: 1665 dates: 1665
Scraping: https://lifehacker.com/latest/page/85 titles: 1685 links: 1685 dates: 1685
Scraping: https://lifehacker.com/latest/page/86 titles: 1705 links: 1705 dates: 1705
Scraping: https://lifehacker.com/latest/page/87 titles: 1725 links: 1725 dates: 1725
Scraping: https://lifehacker.com/latest/page/88 titles: 1745 links: 1745 dates: 1745
Scraping: https://lifehacker.com/latest/page/89 titles: 1765 links: 1765 dates: 1765
Scraping: https://lifehacker.com/latest/page/90 titles: 1785 links: 1785 dates: 1785
Scraping: https://lifehacker.com/latest/page/91 titles: 1805 links: 1805 dates: 1805
Scraping: https://lifehacker.com/latest/page/92 titles: 1825 links: 1825 dates: 1825
Scraping: https://lifehacker.com/latest/page/93 titles: 1845 links: 1845 dates: 1845
Scraping: https://lifehacker.com/latest/page/94 titles: 1865 links: 1865 dates: 1865
Scraping: https://lifehacker.com/latest/page/95 titles: 1885 links: 1885 dates: 1885
Scraping: https://lifehacker.com/latest/page/96 titles: 1905 links: 1905 dates: 1905
Scraping: https://lifehacker.com/latest/page/97 titles: 1925 links: 1925 dates: 1925
Scraping: https://lifehacker.com/latest/page/98 titles: 1945 links: 1945 dates: 1945
Scraping: https://lifehacker.com/latest/page/99 titles: 1965 links: 1965 dates: 1965
Scraping: https://lifehacker.com/latest/page/100 titles: 1985 links: 1985 dates: 1985
Scraping: https://lifehacker.com/latest/page/101 titles: 2005 links: 2005 dates: 2005
Scraping: https://lifehacker.com/latest/page/102 titles: 2025 links: 2025 dates: 2025
Scraping: https://lifehacker.com/latest/page/103 titles: 2045 links: 2045 dates: 2045
Scraping: https://lifehacker.com/latest/page/104 titles: 2065 links: 2065 dates: 2065
Scraping: https://lifehacker.com/latest/page/105 titles: 2085 links: 2085 dates: 2085
Scraping: https://lifehacker.com/latest/page/106 titles: 2105 links: 2105 dates: 2105
Scraping: https://lifehacker.com/latest/page/107 titles: 2125 links: 2125 dates: 2125
Scraping: https://lifehacker.com/latest/page/108 titles: 2145 links: 2145 dates: 2145
Scraping: https://lifehacker.com/latest/page/109 titles: 2165 links: 2165 dates: 2165
Scraping: https://lifehacker.com/latest/page/110 titles: 2185 links: 2185 dates: 2185
Scraping: https://lifehacker.com/latest/page/111 titles: 2205 links: 2205 dates: 2205
Scraping: https://lifehacker.com/latest/page/112 titles: 2225 links: 2225 dates: 2225
Scraping: https://lifehacker.com/latest/page/113 titles: 2245 links: 2245 dates: 2245
Scraping: https://lifehacker.com/latest/page/114 titles: 2265 links: 2265 dates: 2265
Scraping: https://lifehacker.com/latest/page/115 titles: 2285 links: 2285 dates: 2285
Scraping: https://lifehacker.com/latest/page/116 titles: 2305 links: 2305 dates: 2305
Scraping: https://lifehacker.com/latest/page/117 titles: 2325 links: 2325 dates: 2325
Scraping: https://lifehacker.com/latest/page/118 titles: 2345 links: 2345 dates: 2345
Scraping: https://lifehacker.com/latest/page/119 titles: 2365 links: 2365 dates: 2365
Scraping: https://lifehacker.com/latest/page/120 titles: 2385 links: 2385 dates: 2385
Scraping: https://lifehacker.com/latest/page/121 titles: 2405 links: 2405 dates: 2405
Scraping: https://lifehacker.com/latest/page/122 titles: 2425 links: 2425 dates: 2425
Scraping: https://lifehacker.com/latest/page/123 titles: 2445 links: 2445 dates: 2445
Scraping: https://lifehacker.com/latest/page/124 titles: 2465 links: 2465 dates: 2465
Scraping: https://lifehacker.com/latest/page/125 titles: 2485 links: 2485 dates: 2485
Scraping: https://lifehacker.com/latest/page/126 titles: 2505 links: 2505 dates: 2505
Scraping: https://lifehacker.com/latest/page/127 titles: 2525 links: 2525 dates: 2525
Scraping: https://lifehacker.com/latest/page/128 titles: 2545 links: 2545 dates: 2545
Scraping: https://lifehacker.com/latest/page/129 titles: 2565 links: 2565 dates: 2565
Scraping: https://lifehacker.com/latest/page/130 titles: 2585 links: 2585 dates: 2585
Scraping: https://lifehacker.com/latest/page/131 titles: 2605 links: 2605 dates: 2605
Scraping: https://lifehacker.com/latest/page/132 titles: 2625 links: 2625 dates: 2625
Scraping: https://lifehacker.com/latest/page/133 titles: 2645 links: 2645 dates: 2645
Scraping: https://lifehacker.com/latest/page/134 titles: 2665 links: 2665 dates: 2665
Scraping: https://lifehacker.com/latest/page/135 titles: 2685 links: 2685 dates: 2685
Scraping: https://lifehacker.com/latest/page/136 titles: 2705 links: 2705 dates: 2705
Scraping: https://lifehacker.com/latest/page/137 titles: 2725 links: 2725 dates: 2725
Scraping: https://lifehacker.com/latest/page/138 titles: 2745 links: 2745 dates: 2745
Scraping: https://lifehacker.com/latest/page/139 titles: 2765 links: 2765 dates: 2765
Scraping: https://lifehacker.com/latest/page/140 titles: 2785 links: 2785 dates: 2785
Scraping: https://lifehacker.com/latest/page/141 titles: 2805 links: 2805 dates: 2805
Scraping: https://lifehacker.com/latest/page/142 titles: 2825 links: 2825 dates: 2825
Scraping: https://lifehacker.com/latest/page/143 titles: 2845 links: 2845 dates: 2845
Scraping: https://lifehacker.com/latest/page/144 titles: 2865 links: 2865 dates: 2865
Scraping: https://lifehacker.com/latest/page/145 titles: 2885 links: 2885 dates: 2885
Scraping: https://lifehacker.com/latest/page/146 titles: 2905 links: 2905 dates: 2905
Scraping: https://lifehacker.com/latest/page/147 titles: 2925 links: 2925 dates: 2925
Scraping: https://lifehacker.com/latest/page/148 titles: 2945 links: 2945 dates: 2945
Scraping: https://lifehacker.com/latest/page/149 titles: 2965 links: 2965 dates: 2965
Scraping: https://lifehacker.com/latest/page/150 titles: 2985 links: 2985 dates: 2985
Scraping: https://lifehacker.com/latest/page/151 titles: 3005 links: 3005 dates: 3005
Scraping: https://lifehacker.com/latest/page/152 titles: 3025 links: 3025 dates: 3025
Scraping: https://lifehacker.com/latest/page/153 titles: 3045 links: 3045 dates: 3045
Scraping: https://lifehacker.com/latest/page/154 titles: 3065 links: 3065 dates: 3065
Scraping: https://lifehacker.com/latest/page/155 titles: 3085 links: 3085 dates: 3085
Scraping: https://lifehacker.com/latest/page/156 titles: 3105 links: 3105 dates: 3105
Scraping: https://lifehacker.com/latest/page/157 titles: 3125 links: 3125 dates: 3125
Scraping: https://lifehacker.com/latest/page/158 titles: 3145 links: 3145 dates: 3145
Scraping: https://lifehacker.com/latest/page/159 titles: 3165 links: 3165 dates: 3165
Scraping: https://lifehacker.com/latest/page/160 titles: 3185 links: 3185 dates: 3185
Scraping: https://lifehacker.com/latest/page/161 titles: 3205 links: 3205 dates: 3205
Scraping: https://lifehacker.com/latest/page/162 titles: 3225 links: 3225 dates: 3225
Scraping: https://lifehacker.com/latest/page/163 titles: 3245 links: 3245 dates: 3245
Scraping: https://lifehacker.com/latest/page/164 titles: 3265 links: 3265 dates: 3265
Scraping: https://lifehacker.com/latest/page/165 titles: 3285 links: 3285 dates: 3285
Scraping: https://lifehacker.com/latest/page/166 titles: 3305 links: 3305 dates: 3305
Scraping: https://lifehacker.com/latest/page/167 titles: 3325 links: 3325 dates: 3325
Scraping: https://lifehacker.com/latest/page/168 titles: 3345 links: 3345 dates: 3345
Scraping: https://lifehacker.com/latest/page/169 titles: 3365 links: 3365 dates: 3365
Scraping: https://lifehacker.com/latest/page/170 titles: 3385 links: 3385 dates: 3385
Scraping: https://lifehacker.com/latest/page/171 titles: 3405 links: 3405 dates: 3405
Scraping: https://lifehacker.com/latest/page/172 titles: 3425 links: 3425 dates: 3425
Scraping: https://lifehacker.com/latest/page/173 titles: 3445 links: 3445 dates: 3445
Scraping: https://lifehacker.com/latest/page/174 titles: 3465 links: 3465 dates: 3465
Scraping: https://lifehacker.com/latest/page/175 titles: 3485 links: 3485 dates: 3485
Scraping: https://lifehacker.com/latest/page/176 titles: 3505 links: 3505 dates: 3505
Scraping: https://lifehacker.com/latest/page/177 titles: 3525 links: 3525 dates: 3525
Scraping: https://lifehacker.com/latest/page/178 titles: 3545 links: 3545 dates: 3545
Scraping: https://lifehacker.com/latest/page/179 titles: 3565 links: 3565 dates: 3565
Scraping: https://lifehacker.com/latest/page/180 titles: 3585 links: 3585 dates: 3585
Scraping: https://lifehacker.com/latest/page/181 titles: 3605 links: 3605 dates: 3605
Scraping: https://lifehacker.com/latest/page/182 titles: 3625 links: 3625 dates: 3625
Scraping: https://lifehacker.com/latest/page/183 titles: 3645 links: 3645 dates: 3645
Scraping: https://lifehacker.com/latest/page/184 titles: 3665 links: 3665 dates: 3665
Scraping: https://lifehacker.com/latest/page/185 titles: 3685 links: 3685 dates: 3685
Scraping: https://lifehacker.com/latest/page/186 titles: 3705 links: 3705 dates: 3705
Scraping: https://lifehacker.com/latest/page/187 titles: 3725 links: 3725 dates: 3725
Scraping: https://lifehacker.com/latest/page/188 titles: 3745 links: 3745 dates: 3745
Scraping: https://lifehacker.com/latest/page/189 titles: 3765 links: 3765 dates: 3765
Scraping: https://lifehacker.com/latest/page/190 titles: 3785 links: 3785 dates: 3785
Scraping: https://lifehacker.com/latest/page/191 titles: 3805 links: 3805 dates: 3805
Scraping: https://lifehacker.com/latest/page/192 titles: 3825 links: 3825 dates: 3825
Scraping: https://lifehacker.com/latest/page/193 titles: 3845 links: 3845 dates: 3845
Scraping: https://lifehacker.com/latest/page/194 titles: 3865 links: 3865 dates: 3865
Scraping: https://lifehacker.com/latest/page/195 titles: 3885 links: 3885 dates: 3885
Scraping: https://lifehacker.com/latest/page/196 titles: 3905 links: 3905 dates: 3905
Scraping: https://lifehacker.com/latest/page/197 titles: 3925 links: 3925 dates: 3925
Scraping: https://lifehacker.com/latest/page/198 titles: 3945 links: 3945 dates: 3945
Scraping: https://lifehacker.com/latest/page/199 titles: 3965 links: 3965 dates: 3965
Scraping: https://lifehacker.com/latest/page/200 titles: 3985 links: 3985 dates: 3985
Scraping: https://lifehacker.com/latest/page/201 titles: 4005 links: 4005 dates: 4005
Scraping: https://lifehacker.com/latest/page/202 titles: 4025 links: 4025 dates: 4025
Scraping: https://lifehacker.com/latest/page/203 titles: 4045 links: 4045 dates: 4045
Scraping: https://lifehacker.com/latest/page/204 titles: 4065 links: 4065 dates: 4065
Scraping: https://lifehacker.com/latest/page/205 titles: 4085 links: 4085 dates: 4085
Scraping: https://lifehacker.com/latest/page/206 titles: 4105 links: 4105 dates: 4105
Scraping: https://lifehacker.com/latest/page/207 titles: 4125 links: 4125 dates: 4125
Scraping: https://lifehacker.com/latest/page/208 titles: 4145 links: 4145 dates: 4145
Scraping: https://lifehacker.com/latest/page/209 titles: 4165 links: 4165 dates: 4165
Scraping: https://lifehacker.com/latest/page/210 titles: 4185 links: 4185 dates: 4185
Scraping: https://lifehacker.com/latest/page/211 titles: 4205 links: 4205 dates: 4205
Scraping: https://lifehacker.com/latest/page/212 titles: 4225 links: 4225 dates: 4225
Scraping: https://lifehacker.com/latest/page/213 titles: 4245 links: 4245 dates: 4245
Scraping: https://lifehacker.com/latest/page/214 titles: 4265 links: 4265 dates: 4265
Scraping: https://lifehacker.com/latest/page/215 titles: 4285 links: 4285 dates: 4285
Scraping: https://lifehacker.com/latest/page/216 titles: 4305 links: 4305 dates: 4305
Scraping: https://lifehacker.com/latest/page/217 titles: 4325 links: 4325 dates: 4325
Scraping: https://lifehacker.com/latest/page/218 titles: 4345 links: 4345 dates: 4345
Scraping: https://lifehacker.com/latest/page/219 titles: 4365 links: 4365 dates: 4365
Scraping: https://lifehacker.com/latest/page/220 titles: 4385 links: 4385 dates: 4385
Scraping: https://lifehacker.com/latest/page/221 titles: 4405 links: 4405 dates: 4405
Scraping: https://lifehacker.com/latest/page/222 titles: 4425 links: 4425 dates: 4425
Scraping: https://lifehacker.com/latest/page/223 titles: 4445 links: 4445 dates: 4445
Scraping: https://lifehacker.com/latest/page/224 titles: 4465 links: 4465 dates: 4465
Scraping: https://lifehacker.com/latest/page/225 titles: 4485 links: 4485 dates: 4485
Scraping: https://lifehacker.com/latest/page/226 titles: 4505 links: 4505 dates: 4505
Scraping: https://lifehacker.com/latest/page/227 titles: 4525 links: 4525 dates: 4525
Scraping: https://lifehacker.com/latest/page/228 titles: 4545 links: 4545 dates: 4545
Scraping: https://lifehacker.com/latest/page/229 titles: 4565 links: 4565 dates: 4565
Scraping: https://lifehacker.com/latest/page/230 titles: 4585 links: 4585 dates: 4585
Scraping: https://lifehacker.com/latest/page/231 titles: 4605 links: 4605 dates: 4605
Scraping: https://lifehacker.com/latest/page/232 titles: 4625 links: 4625 dates: 4625
Scraping: https://lifehacker.com/latest/page/233 titles: 4645 links: 4645 dates: 4645
Scraping: https://lifehacker.com/latest/page/234 titles: 4665 links: 4665 dates: 4665
Scraping: https://lifehacker.com/latest/page/235 titles: 4685 links: 4685 dates: 4685

In [39]:
titles

['The Garmin Forerunner 265 and 965 Have Never Been Priced This Low',
 'This Fire TV Stick HD Is Less Than $20 Right Now',
 'Four Unofficial Ways to Customize MacOS',
 'How to Talk to a Real Human in Customer Service (and Get What You Want)',
 "'Theme' Every Work Day for a More Productive Week",
 "'Flowtime' Is a More Flexible Alternative to the Pomodoro Technique",
 'You Can Get This Dragon G3X Ultra Wired Gaming Headset on Sale for Just $50',
 'RayNeo Air 3S Pro Review: These Smart Glasses Deliver an Attractive HD Display at a (Relatively) Low Price',
 "Google's AI Shopping Push Is Better for Business Than It Is for You",
 "Spotify's New AI-Powered Audiobook Recaps Will Remind You Where You Left Off",
 'The Google Play Store Is Making It Easy to Remotely Uninstall Apps From Your Other Android Devices',
 'Google Can Now Robocall Stores for You to Ask If They Have What You Want',
 'Lifehacker Deals Live Blog: The Best Sales We’ve Found, All in One Place',
 "The Four Best Paint Additives I've Used in My Own House (That You Should Try Too)",
 "13 Shows like 'Monster: The Ed Gein Story' You Should Watch Next",
 'OpenAI Has a New Model Powering ChatGPT',
 'Google Is Rolling Out ‘Agentic Checkout’ to Make Your Purchases for You',
 'The Best Early Black Friday Deals on MacBooks Air Laptops',
 'I Test Smartwatches and Fitness Trackers, and These Are the Prices You Should Look Out for on Black Friday',
 "Google's AI Mode Can Now Work Like a Virtual Sales Associate",
 'Six of the Best YouTube Channels for Running Workouts',
 'All the New Features Coming to iOS 26.2',
 'My Favorite Amazon Deal of the Day: The 13-Inch M4 MacBook Air',
 "What RCS Messaging Between iOS and Android Can and Can't Do (Yet)",
 'This New Hotel Reservation Scam Is Fooling People Who Use Sites Like Booking.com']

In [5]:
len(titles)

26125

In [6]:
len(links)

26125

In [7]:
len(dates)

26125

In [8]:
df = pd.DataFrame(data={'titles':titles,'links':links,'dates':dates})

In [9]:
df.head()

,titles,links,dates
0,Beware These Black Friday Shopping Scams,/money/beware-these-black-friday-shopping-scams,"November 14, 2025"
1,How to Set Up Alexa Wishlist Alerts for Black ...,/how-to-set-up-alexa-wishlist-alerts,"November 14, 2025"
2,Lifehacker Deals Live Blog: The Best Sales We’...,/best-deals-live-blog,"November 14, 2025"
3,Older Pixel Devices Can Now Record Calls Direc...,/tech/older-pixel-phones-can-now-record-calls-...,"November 14, 2025"
4,"I Test Smartwatches and Fitness Trackers, and ...",/health/best-deals-on-smartwatches-and-fitness...,"November 14, 2025"

In [10]:
df.to_csv('lifehacker_1.csv',index=False)

In [2]:
import json
import multiprocessing
import random
from datetime import datetime
import numpy as np

In [4]:
new_df = pd.read_csv('lifehacker_contents.csv')

In [63]:
df = pd.read_csv('lifehacker_1.csv')

In [64]:
df.head()

,titles,links,dates
0,Beware These Black Friday Shopping Scams,/money/beware-these-black-friday-shopping-scams,"November 14, 2025"
1,How to Set Up Alexa Wishlist Alerts for Black ...,/how-to-set-up-alexa-wishlist-alerts,"November 14, 2025"
2,Lifehacker Deals Live Blog: The Best Sales We’...,/best-deals-live-blog,"November 14, 2025"
3,Older Pixel Devices Can Now Record Calls Direc...,/tech/older-pixel-phones-can-now-record-calls-...,"November 14, 2025"
4,"I Test Smartwatches and Fitness Trackers, and ...",/health/best-deals-on-smartwatches-and-fitness...,"November 14, 2025"

In [19]:
df['content'] = None

In [6]:
links=df['links']
links = df['links'].tolist()
len(links)

26125

In [9]:
idxs = [f"{s[0]}-{s[-1]}" for s in np.array_split(np.arange(len(links)), 24)]

In [11]:
idxData = [(int(idxs[i].split('-')[0]),int(idxs[i].split('-')[1]),4-i%4) for i in range(len(idxs))]

In [12]:
idxData

[(0, 1088, 4),
 (1089, 2177, 3),
 (2178, 3266, 2),
 (3267, 4355, 1),
 (4356, 5444, 4),
 (5445, 6533, 3),
 (6534, 7622, 2),
 (7623, 8711, 1),
 (8712, 9800, 4),
 (9801, 10889, 3),
 (10890, 11978, 2),
 (11979, 13067, 1),
 (13068, 14156, 4),
 (14157, 15244, 3),
 (15245, 16332, 2),
 (16333, 17420, 1),
 (17421, 18508, 4),
 (18509, 19596, 3),
 (19597, 20684, 2),
 (20685, 21772, 1),
 (21773, 22860, 4),
 (22861, 23948, 3),
 (23949, 25036, 2),
 (25037, 26124, 1)]

In [27]:
quarters = [("January","February","March"),("April","May","June"),("July","August","September"),("October","November","December")]

In [95]:
def new_driver():
    options = uc.ChromeOptions()
    driver = uc.Chrome(
        use_subprocess=True,
        options=options,
        client_config={
            "connection_timeout": 300,  
            "read_timeout": 300          
        }
    )
    return driver
driver=new_driver()

In [28]:
df['year'] = df['dates'].map(lambda x:x[-4:])

In [35]:
df.head()

,titles,links,dates,content,year
0,Beware These Black Friday Shopping Scams,/money/beware-these-black-friday-shopping-scams,"November 14, 2025",None,2025
1,How to Set Up Alexa Wishlist Alerts for Black ...,/how-to-set-up-alexa-wishlist-alerts,"November 14, 2025",None,2025
2,Lifehacker Deals Live Blog: The Best Sales We’...,/best-deals-live-blog,"November 14, 2025",None,2025
3,Older Pixel Devices Can Now Record Calls Direc...,/tech/older-pixel-phones-can-now-record-calls-...,"November 14, 2025",None,2025
4,"I Test Smartwatches and Fitness Trackers, and ...",/health/best-deals-on-smartwatches-and-fitness...,"November 14, 2025",None,2025

In [36]:
new_df = pd.DataFrame(data={"titles":[],"links":[],"dates":[],"content":[],"year":[]},columns=["titles","links","dates","content","year"])

In [42]:
for year in ["2025","2024","2023","2022","2021","2020"]:
    for q in [1,2,3,4]:
        cur_year = df[df['year'] == year]
        selected = []
        notselected = set()  

        while len(selected) < 500:
            sel = cur_year.sample(n=1)
            idx = sel.index[0]  

            if idx in notselected:
                continue  
            notselected.add(idx)

            date_str = sel.at[idx, 'dates']  
            if date_str.split()[0] in quarters[q-1]:
                selected.append(sel.iloc[0])  
                
            if len(notselected) >= len(cur_year):
                break  
                
        selected_df = pd.DataFrame(selected)
        new_df = pd.concat([new_df, selected_df], ignore_index=True)

In [44]:
new_df

,titles,links,dates,content,year
0,Eight Ways to Speed Up Your iCloud Sync,/how-to-speed-up-icloud-sync,"February 13, 2025",None,2025
1,The Vvolt Centauri II Just Became My New Favor...,/tech/vvolt-centauri-ii-e-bike-review,"January 13, 2025",None,2025
2,How to Delete Your Facebook Account,/tech/how-to-delete-your-facebook-account,"January 13, 2025",None,2025
3,'Fix Me a Plate' Is the Cookbook You Need for ...,/fix-me-a-plate-cookbook-review,"February 21, 2025",None,2025
4,The Safe (and Unsafe) Flowers to Buy Your Vale...,/home/which-flowers-are-safe-and-unsafe-for-pets,"February 10, 2025",None,2025
...,...,...,...,...,...
11995,Is a Warm Smoothie a Thing You Need?,/is-a-warm-smoothie-a-thing-you-need-1845728210,"November 23, 2020",None,2020
11996,How to Safely Return to Exercise After You've ...,/how-to-safely-return-to-exercise-after-youve-...,"November 18, 2020",None,2020
11997,Why You Should Name a Guardian for Your Kids R...,/why-you-should-name-a-guardian-for-your-kids-...,"October 27, 2020",None,2020
11998,Leave Old Toys Under the Tree for Santa to Del...,/leave-old-toys-under-the-tree-for-santa-to-de...,"December 23, 2020",None,2020
11999,How Transgender Customers Can Use Their Chosen...,/how-transgender-customers-can-use-their-chose...,"October 21, 2020",None,2020

In [46]:
new_df.to_csv('lifehacker_contents.csv',index=False)

In [16]:
display_handle = display("", display_id=True)
for idx,row in new_df.iterrows():
    try:
        driver.get("https://lifehacker.com"+row['links'])
        time.sleep(random.uniform(3, 7.0)) 
        html = driver.page_source
    
        if "Just a moment" in html:
            print("Cloudflare.")
            time.sleep(10)
            html = driver.page_source
            if "Just a moment" in html:
                print("Blocked, skip page")
                continue
        
        soup = BeautifulSoup(html, "html.parser")

        content = soup.select_one('article.editor-content')
        if content:
            new_df.at[idx, 'content'] = soup.select_one('article.editor-content').get_text(separator=" ", strip=True)
            
        display_handle.update(f"Scraping: {row['links']} contents: {new_df['content'].notnull().sum()} idx: {idx}")
        if(idx%500==0):
            new_df.to_csv('lifehacker_contents.csv',index=False)
        
    except Exception as e:
        print("Error:", e)
        time.sleep(10)

'Scraping: /how-to-get-woodpeckers-to-fuck-off-1848847616 contents: 6284 idx: 6595'

Error: Message: tab crashed
  (Session info: chrome=142.0.7444.163)

Error: Message: tab crashed
  (Session info: chrome=142.0.7444.163)

Error: Message: tab crashed
  (Session info: chrome=142.0.7444.163)

Error: Message: tab crashed
  (Session info: chrome=142.0.7444.163)

Error: Message: tab crashed
  (Session info: chrome=142.0.7444.163)

Error: Message: tab crashed
  (Session info: chrome=142.0.7444.163)

Error: Message: tab crashed
  (Session info: chrome=142.0.7444.163)

Error: Message: tab crashed
  (Session info: chrome=142.0.7444.163)

Error: Message: tab crashed
  (Session info: chrome=142.0.7444.163)

Error: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=142.0.7444.163)
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x784093
	0x7840d4
	0x58e71d
	0x56c32d
	0x60329e
	0x61e749
	0x5fc706
	0x5cda30
	0x5ced54
	0x9f5744
	0x9f091a
	0x7ac322
	0x79c458
	0x7a31dd
	0x78c408
	0x78c5cc
	0x77675a
	0x774b7d59
	0x77d7b79b
	0x77d7b71f

Error: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=142.0.7444.163)
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x784093
	0x7840d4
	0x58e71d
	0x56c32d
	0x60329e
	0x61e749
	0x5fc706
	0x5cda30
	0x5ced54
	0x9f5744
	0x9f091a
	0x7ac322
	0x79c458
	0x7a31dd
	0x78c408
	0x78c5cc
	0x77675a
	0x774b7d59
	0x77d7b79b
	0x77d7b71f

Error: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=142.0.7444.163)
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x784093
	0x7840d4
	0x58e71d
	0x56c32d
	0x60329e
	0x61e749
	0x5fc706
	0x5cda30
	0x5ced54
	0x9f5744
	0x9f091a
	0x7ac322
	0x79c458
	0x7a31dd
	0x78c408
	0x78c5cc
	0x77675a
	0x774b7d59
	0x77d7b79b
	0x77d7b71f

KeyboardInterrupt:

In [18]:
# tab crashed

In [20]:
display_handle = display("", display_id=True)
for idx,row in new_df.iloc[6501:].iterrows():
    try:
        driver.get("https://lifehacker.com"+row['links'])
        time.sleep(random.uniform(3, 7.0)) 
        html = driver.page_source
    
        if "Just a moment" in html:
            print("Cloudflare.")
            time.sleep(10)
            html = driver.page_source
            if "Just a moment" in html:
                print("Blocked, skip page")
                continue
        
        soup = BeautifulSoup(html, "html.parser")

        content = soup.select_one('article.editor-content')
        if content:
            new_df.at[idx, 'content'] = soup.select_one('article.editor-content').get_text(separator=" ", strip=True)
            
        display_handle.update(f"Scraping: {row['links']} contents: {new_df['content'].notnull().sum()} idx: {idx}")
        if(idx%500==0):
            new_df.to_csv('lifehacker_contents.csv',index=False)
        
    except Exception as e:
        print("Error:", e)
        driver.quit()
        driver = new_driver()
        time.sleep(10)

'Scraping: /how-transgender-customers-can-use-their-chosen-name-on-1845436821 contents: 11084 idx: 11999'

Error: HTTPConnectionPool(host='localhost', port=59177): Read timed out. (read timeout=120)
Error: HTTPConnectionPool(host='localhost', port=63985): Read timed out. (read timeout=120)
Error: HTTPConnectionPool(host='localhost', port=63133): Read timed out. (read timeout=120)
Cloudflare.
Blocked, skip page

In [32]:
df_null = new_df[new_df['content'] == '']

In [33]:
df_null

,titles,links,dates,content,year
8172,How to Stop Mixing Up 'Than' and 'Then',/how-to-stop-mixing-up-than-and-then-1846581788,"March 30, 2021",,2021
8659,You Should Make Pasta Salad With Store-Bought ...,/you-should-make-pasta-salad-with-store-bought...,"June 23, 2021",,2021

In [37]:
df_null2 = new_df[new_df.isnull().any(axis=1)]

In [38]:
df_null2

,titles,links,dates,content,year
11,The Powerbeats Pro 2 Are My New Favorite Worko...,/health/apple-beats-powerbeats-pro-2-review,"March 7, 2025",NaN,2025
46,The Asus Zenbook A14 Is Light on Everything bu...,/tech/asus-zenbook-a14-review,"March 24, 2025",NaN,2025
72,Which Is Better: Whoop vs. Oura,/health/oura-vs-whoop,"February 5, 2025",NaN,2025
82,Brainscape Makes Flashcard Generation Easy,/tech/brainscape-flashcard-app-review,"March 24, 2025",NaN,2025
84,"Narwal's Freo Z Ultra Is a Great Mop, but a Wa...",/tech/narwal-freo-z-ultra-is-a-great-mop-but-a...,"March 14, 2025",NaN,2025
...,...,...,...,...,...
11926,7 Ways to Store an Overwhelming Amount of Toys,/7-ways-to-store-an-overwhelming-amount-of-toy...,"December 29, 2020",NaN,2020
11929,13 Shows You Can Watch Without Actually Lookin...,/13-shows-you-can-watch-without-actually-looki...,"November 24, 2020",NaN,2020
11938,Clean Your Kitchen and More With Bar Keepers F...,/clean-your-kitchen-and-more-with-barkeepers-f...,"November 3, 2020",NaN,2020
11964,How to Take the Best Photos With Your iPhone,/how-to-take-the-best-photos-with-your-iphone-...,"October 1, 2020",NaN,2020
11995,Is a Warm Smoothie a Thing You Need?,/is-a-warm-smoothie-a-thing-you-need-1845728210,"November 23, 2020",NaN,2020

In [40]:
df_null = pd.concat([df_null,df_null2],ignore_index=False)

In [41]:
df_null

,titles,links,dates,content,year
8172,How to Stop Mixing Up 'Than' and 'Then',/how-to-stop-mixing-up-than-and-then-1846581788,"March 30, 2021",,2021
8659,You Should Make Pasta Salad With Store-Bought ...,/you-should-make-pasta-salad-with-store-bought...,"June 23, 2021",,2021
11,The Powerbeats Pro 2 Are My New Favorite Worko...,/health/apple-beats-powerbeats-pro-2-review,"March 7, 2025",NaN,2025
46,The Asus Zenbook A14 Is Light on Everything bu...,/tech/asus-zenbook-a14-review,"March 24, 2025",NaN,2025
72,Which Is Better: Whoop vs. Oura,/health/oura-vs-whoop,"February 5, 2025",NaN,2025
...,...,...,...,...,...
11926,7 Ways to Store an Overwhelming Amount of Toys,/7-ways-to-store-an-overwhelming-amount-of-toy...,"December 29, 2020",NaN,2020
11929,13 Shows You Can Watch Without Actually Lookin...,/13-shows-you-can-watch-without-actually-looki...,"November 24, 2020",NaN,2020
11938,Clean Your Kitchen and More With Bar Keepers F...,/clean-your-kitchen-and-more-with-barkeepers-f...,"November 3, 2020",NaN,2020
11964,How to Take the Best Photos With Your iPhone,/how-to-take-the-best-photos-with-your-iphone-...,"October 1, 2020",NaN,2020
11995,Is a Warm Smoothie a Thing You Need?,/is-a-warm-smoothie-a-thing-you-need-1845728210,"November 23, 2020",NaN,2020

In [57]:
display_handle = display("", display_id=True)
updated = new_df.copy()
for idx,row in df_null.iterrows():
    try:
        driver.get("https://lifehacker.com"+row['links'])
        time.sleep(random.uniform(3, 7.0)) 
        html = driver.page_source
    
        if "Just a moment" in html:
            print("Cloudflare.")
            time.sleep(10)
            html = driver.page_source
            if "Just a moment" in html:
                print("Blocked, skip page")
                continue
        
        soup = BeautifulSoup(html, "html.parser")

        content = soup.select_one('.editor-content')
        if content:
            updated.at[idx, 'content'] = soup.select_one('.editor-content').get_text(separator=" ", strip=True)
            
        display_handle.update(f"Scraping: {row['links']} idx: {idx} null:{updated['content'].isnull().sum()}")
        
    except Exception as e:
        print("Error:", e)
        driver.quit()
        driver = new_driver()
        time.sleep(10)

'Scraping: /is-a-warm-smoothie-a-thing-you-need-1845728210 idx: 11995 null:133'

Cloudflare.
Blocked, skip page

In [60]:
updated[updated['content'].isnull()]

,titles,links,dates,content,year
2443,Today's NYT Connections Hints (and Answer) for...,/entertainment/nyt-connections-answer-today-fe...,"February 4, 2024",NaN,2024
2661,A Guide to Gearing Up Your Kitchen,/series/a-guide-to-gearing-up-your-kitchen,"April 29, 2024",NaN,2024
2698,Find Your Fit Tech,/series/find-your-fit-tech,"April 26, 2024",NaN,2024
4005,You’ve Been Playing ‘Super Mario Bros.’ Wrong ...,/you-ve-been-playing-super-mario-bros-wrong-th...,"January 3, 2023",NaN,2023
4013,"Yes, Any Drink Can Be Cake Icing",/yes-any-drink-can-be-cake-icing-1850155174,"February 24, 2023",NaN,2023
...,...,...,...,...,...
8281,Home Electrical Projects You Can Totally Handl...,/home-electrical-projects-you-can-totally-hand...,"March 15, 2021",NaN,2021
8491,Cultivate the Perfect Evening Routine to Avoid...,/cultivate-the-perfect-evening-routine-to-avoi...,"January 7, 2021",NaN,2021
8845,How to Make Sense of What Apple Has Done to th...,/how-to-make-sense-of-what-apple-has-done-to-t...,"June 22, 2021",NaN,2021
9651,How to Remove Followers on Twitter,/how-to-remove-followers-on-twitter-1848067495,"November 16, 2021",NaN,2021
11514,How to Set Up Windows 10 on Your PC,/how-to-set-up-your-windows-laptop-from-scratc...,"December 28, 2020",NaN,2020

In [67]:
new_df.shape

(12000, 5)

In [137]:
new_df=updated.copy()

In [138]:
new_df.to_csv('lifehacker_contents.csv',index=False)

In [115]:
df['month'] = df['dates'].map(lambda x: datetime.strptime(x, "%B %d, %Y").month)

In [116]:
df['year'] = df['dates'].map(lambda x: datetime.strptime(x, "%B %d, %Y").year)

In [73]:
df.head()

,titles,links,dates,month,year
0,Beware These Black Friday Shopping Scams,/money/beware-these-black-friday-shopping-scams,"November 14, 2025",2,2024
1,How to Set Up Alexa Wishlist Alerts for Black ...,/how-to-set-up-alexa-wishlist-alerts,"November 14, 2025",2,2024
2,Lifehacker Deals Live Blog: The Best Sales We’...,/best-deals-live-blog,"November 14, 2025",2,2024
3,Older Pixel Devices Can Now Record Calls Direc...,/tech/older-pixel-phones-can-now-record-calls-...,"November 14, 2025",2,2024
4,"I Test Smartwatches and Fitness Trackers, and ...",/health/best-deals-on-smartwatches-and-fitness...,"November 14, 2025",2,2024

In [124]:
updated = new_df.copy()

In [91]:
def get_quarter_range(month):
    if month in [1,2,3]:
        return [1,2,3]
    if month in [4,5,6]:
        return [4,5,6]
    if month in [7,8,9]:
        return [7,8,9]
    return [10,11,12]

In [129]:
display_handle = display("", display_id=True)
for idx,row in updated[updated['content']==''].iterrows():
    valid = False
    date_object = datetime.strptime(row['dates'], "%B %d, %Y")
    month = date_object.month
    month_range = get_quarter_range(month)
    year = date_object.year
    filtered = df[(df['month'] == month) & (df['year'] == year)]
    while not valid:
        selected = filtered.sample(n=1)
        try:
            driver.get("https://lifehacker.com"+selected['links'].iloc[0])
            time.sleep(random.uniform(3, 7.0)) 
            html = driver.page_source
        
            if "Just a moment" in html:
                print("Cloudflare.")
                time.sleep(10)
                html = driver.page_source
                if "Just a moment" in html:
                    print("Blocked, skip page")
                    continue
            
            soup = BeautifulSoup(html, "html.parser")
    
            content = soup.select_one('.editor-content')
            if content:
                updated.at[idx,'titles'] = selected['titles'].iloc[0]
                updated.at[idx,'links'] = selected['links'].iloc[0]
                updated.at[idx,'date'] = selected['dates'].iloc[0]
                updated.at[idx, 'content'] = soup.select_one('.editor-content').get_text(separator=" ", strip=True)
                valid = True
            display_handle.update(f"Scraping: {selected['links'].iloc[0]} idx: {idx} null:{updated['content'].isnull().sum()}")
            
        except Exception as e:
            print("Error:", e)
            driver.quit()
            driver = new_driver()
            time.sleep(10)

'Scraping: /how-to-make-sure-you-get-your-monthly-child-tax-credit-1847055859 idx: 8659 null:0'